import { resolvePhysicsSpec } from "./physicsSpec.js";
import type { ResolvedShooterGameSpec } from "./gameSpecTypes.js";

export const DEFAULT_SHOOTER_GAME_SPEC: ResolvedShooterGameSpec = {
  worldWidth: 1600,
  worldHeight: 960,
  playerSpeed: 180,
  enemySpeed: 72,
  enemySpawnInterval: 1.0,
  bulletSpeed: 360,
  fireCooldown: 0.12,
  bulletLifetime: 1.8,
  projectileArc: {
    enabled: false,
    launchHeight: 0,
    zVelocity: 0,
    gravity: 0,
    hitHeight: 0,
  },
  playerWidth: 36,
  playerHeight: 36,
  enemyWidth: 24,
  enemyHeight: 24,
  bulletWidth: 8,
  bulletHeight: 8,
  playerAnimationFrames: 1,
  playerAnimationFps: 0,
  playerAnimationColumns: 1,
  playerAnimationRows: 1,
  playerAnimationIdleRow: 0,
  playerAnimationIdleFrames: 1,
  playerAnimationIdleFps: 1,
  playerAnimationMoveRow: 0,
  playerAnimationMoveFrames: 1,
  playerAnimationMoveFps: 1,
  enemyAnimationFrames: 1,
  enemyAnimationFps: 0,
  enemyAnimationColumns: 1,
  enemyAnimationRows: 1,
  enemyAnimationIdleRow: 0,
  enemyAnimationIdleFrames: 1,
  enemyAnimationIdleFps: 1,
  enemyAnimationMoveRow: 0,
  enemyAnimationMoveFrames: 1,
  enemyAnimationMoveFps: 1,
  bulletAnimationFrames: 1,
  bulletAnimationFps: 0,
  bulletAnimationColumns: 1,
  bulletAnimationRows: 1,
  bulletAnimationIdleRow: 0,
  bulletAnimationIdleFrames: 1,
  bulletAnimationIdleFps: 1,
  bulletAnimationMoveRow: 0,
  bulletAnimationMoveFrames: 1,
  bulletAnimationMoveFps: 1,
  enemyBehavior: "chase",
  enemyBehaviorCode: 0,
  enemySpawnPattern: "edge",
  enemySpawnPatternCode: 0,
  enemyHealth: 1,
  bulletDamage: 1,
  scoreReward: 1,
  orbitRadius: 180,
  orbitRadialBand: 24,
  cameraPreset: "follow",
  cameraPresetCode: 0,
  cameraDeadZoneWidth: 160,
  cameraDeadZoneHeight: 96,
  cameraLookAheadDistance: 96,
  cameraShakeAmplitude: 6,
  cameraShakeFrequency: 8,
  atlasFrames: {},
  playerCollider: {
    type: "aabb",
    halfWidth: 18,
    halfHeight: 18,
    offsetX: 0,
    offsetY: 0,
    enabled: true,
    trigger: true,
  },
  enemyCollider: {
    type: "aabb",
    halfWidth: 12,
    halfHeight: 12,
    offsetX: 0,
    offsetY: 0,
    enabled: true,
    trigger: true,
  },
  bulletCollider: {
    type: "aabb",
    halfWidth: 4,
    halfHeight: 4,
    offsetX: 0,
    offsetY: 0,
    enabled: true,
    trigger: true,
  },
  waves: [],
  audioMasterVolume: 1,
  audioSfxVolume: 1,
  shootVolume: 0.35,
  shootPitch: 1,
  hitVolume: 0.45,
  hitPitch: 1,
  gameOverVolume: 0.65,
  gameOverPitch: 0.9,
  postProcessing: [],
  physics: resolvePhysicsSpec(undefined),
  content: {
    dialogueGraphs: {},
    cutscenes: {},
  },
};
export const TILE_SLOPE_MIN_HORIZONTAL_SPAN = 0.0001;
export const MAX_ATLAS_ANIMATION_FRAMES = 32;
export const DEFAULT_PHYSICS_MATERIAL_RESTITUTION = 0;
export const DEFAULT_PHYSICS_MATERIAL_FRICTION = 0.4;
export const DEFAULT_PHYSICS_MATERIAL_DENSITY = 1;
export const DEFAULT_PHYSICS_MATERIAL_SCALE = 1;
