export { applyShooterGameSpec } from "./gameSpecApply.js";
export { resolveShooterGameSpec } from "./gameSpecResolve.js";
export type {
  ShooterGameSpec,
  ShooterEnemyPresetSpec,
  ShooterEnemyOrbitSpec,
  ShooterWaveSpec,
  ShooterAudioSpec,
  ShooterAudioEventPolicySpec,
  ShooterCameraSpec,
  ShooterPrefabSpec,
  ShooterPrefabColliderType,
  ShooterPrefabColliderSpec,
  ShooterPhysicsMaterialSpec,
  ShooterAtlasSpec,
  ShooterTilemapSpec,
  ShooterTileSpec,
  ShooterTileSlopeSpec,
  ShooterTileLayerSpec,
  ShooterAtlasFrameSpec,
  ResolvedShooterAtlasFrame,
  ResolvedShooterTileDefinition,
  ResolvedShooterTileSlopeDefinition,
  ResolvedShooterTileLayer,
  ResolvedShooterTilemap,
  ResolvedShooterPhysicsMaterial,
  ResolvedShooterPrefabColliderBase,
  ResolvedShooterPrefabCollider,
  ResolvedShooterPrefabColliderVertex,
  ResolvedShooterPrefabAabbCollider,
  ResolvedShooterWave,
  ShooterSpriteAnimationSpec,
  ShooterSpriteAnimationStateSpec,
  ShooterAtlasAnimationSpec,
  ShooterAtlasAnimationStateSpec,
  ShooterEnemyBehaviorPreset,
  ShooterEnemySpawnPatternPreset,
  ShooterCameraPreset,
  ResolvedShooterGameSpec,
  ResolvedShooterAtlasAnimation,
  ResolvedShooterAtlasAnimationState,
  ShooterGameSpecTarget,
  ApplyShooterGameSpecOptions,
  ResolveShooterGameSpecOptions,
} from "./gameSpecTypes.js";
