export {
  AnimationTimelinePlayer,
  animationTimelineFrameAt,
  resolveAnimationTimelineSpec,
} from "./animationTimeline";
export {
  applySceneCompositionFragment,
  instantiateSceneFragment,
  resolveSceneCompositionSpec,
} from "./sceneComposition";
export {
  applyBehaviorRecipes,
  behaviorRecipeCommandsForEntity,
  resolveBehaviorRecipeDocument,
} from "./behaviorRecipes";
export {
  captureGameStateSnapshot,
  GAME_STATE_SNAPSHOT_FORMAT,
  GAME_STATE_SNAPSHOT_VERSION,
  hashGameStateSnapshot,
  loadGameStateSnapshotFromStorage,
  parseGameStateSnapshot,
  removeGameStateSnapshotFromStorage,
  restoreGameStateSnapshot,
  saveGameStateSnapshotToStorage,
  stringifyGameStateSnapshot,
  validateGameStateSnapshot,
} from "./gameStateSnapshot";
export type {
  AnimationTimelineEmittedEvent,
  AnimationTimelineEventPayload,
  AnimationTimelineEventSpec,
  AnimationTimelineFrameRef,
  AnimationTimelinePlayerSnapshot,
  AnimationTimelineSpec,
  AnimationTimelineStateSpec,
  AnimationTimelineTransitionSpec,
  AnimationTimelineUpdateOptions,
  AnimationTimelineUpdateResult,
  ResolvedAnimationTimelineEvent,
  ResolvedAnimationTimelineSpec,
  ResolvedAnimationTimelineState,
  ResolvedAnimationTimelineTransition,
} from "./animationTimeline";
export type {
  ApplySceneCompositionOptions,
  InstantiateSceneFragmentOptions,
  ResolveSceneCompositionOptions,
  ResolvedSceneCompositionFragment,
  ResolvedSceneCompositionFragmentInclude,
  ResolvedSceneCompositionFragmentInstance,
  ResolvedSceneCompositionInstance,
  ResolvedSceneCompositionPrefab,
  ResolvedSceneCompositionPrefabVariant,
  ResolvedSceneCompositionSpec,
  ResolvedSceneCompositionTransform,
  SceneCompositionApplyResult,
  SceneCompositionFragmentIncludeSpec,
  SceneCompositionFragmentInstanceSpec,
  SceneCompositionFragmentSpec,
  SceneCompositionJsonValue,
  SceneCompositionPrefabSpec,
  SceneCompositionPrefabVariantSpec,
  SceneCompositionProps,
  SceneCompositionSpec,
  SceneCompositionTarget,
  SceneCompositionTransformSpec,
} from "./sceneComposition";
export type {
  ApplyBehaviorRecipesOptions,
  BehaviorRecipeApplyResult,
  BehaviorRecipeCommand,
  BehaviorRecipeCommandBase,
  BehaviorRecipeCommandOptions,
  BehaviorRecipeDamageTarget,
  BehaviorRecipeDocumentSpec,
  BehaviorRecipeEntrySpec,
  BehaviorRecipeEntitySpec,
  BehaviorRecipeHealthZeroAction,
  BehaviorRecipeKind,
  BehaviorRecipeReferenceSpec,
  BehaviorRecipeRuntimeTarget,
  BehaviorRecipeSpec,
  ChaseBehaviorRecipeSpec,
  ConfigureChaseBehaviorCommand,
  ConfigureDamageBehaviorCommand,
  ConfigureHealthBehaviorCommand,
  ConfigureInteractionBehaviorCommand,
  ConfigurePickupBehaviorCommand,
  DamageBehaviorRecipeSpec,
  HealthBehaviorRecipeSpec,
  InteractionBehaviorRecipeSpec,
  PickupBehaviorRecipeSpec,
  ResolveBehaviorRecipeDocumentOptions,
  ResolvedBehaviorRecipe,
  ResolvedBehaviorRecipeBase,
  ResolvedBehaviorRecipeDocument,
  ResolvedBehaviorRecipeEntity,
  ResolvedChaseBehaviorRecipe,
  ResolvedDamageBehaviorRecipe,
  ResolvedHealthBehaviorRecipe,
  ResolvedInteractionBehaviorRecipe,
  ResolvedPickupBehaviorRecipe,
} from "./behaviorRecipes";
export type {
  CaptureGameStateSnapshotOptions,
  GameStateSceneSnapshot,
  GameStateSnapshot,
  GameStateSnapshotJsonValue,
  GameStateSnapshotRestoreResult,
  GameStateSnapshotStorage,
  RestoreGameStateSnapshotOptions,
} from "./gameStateSnapshot";
export {
  BUILT_IN_SHOOTER_STATE_FORMAT,
  BUILT_IN_SHOOTER_STATE_VERSION,
  validateBuiltInShooterStateSnapshot,
} from "./builtInShooterStateSnapshot";
export type { BuiltInShooterStateSnapshot } from "./builtInShooterStateSnapshot";
export {
  PHYSICS_BODY_STATE_BUFFER_FORMAT,
  PHYSICS_BODY_STATE_BUFFER_VERSION,
  PHYSICS_BODY_STATE_FLOATS_PER_BODY,
  PHYSICS_BODY_STATE_U32S_PER_BODY,
  createEngine,
  createPhysicsBodyStateBufferSnapshot,
} from "./createEngine";
export { createFerrumRuntime } from "./createFerrumRuntime";
export { createRenderer } from "./createRenderer";
export type {
  FerrumRuntime,
  FerrumRuntimeEnvironment,
  FerrumRuntimeFrame,
  FerrumRuntimeOptions,
  FerrumRuntimeRenderer,
  LightingSceneProvider,
  PostProcessProvider,
  SpriteMaterialProvider,
} from "./createFerrumRuntime";
export type { UiOverlayStateProvider } from "./createFerrumRuntime";
export type {
  AssetHost,
  AudioBusConfig,
  CreateEngineOptions,
  EngineLifecycleHooks,
  EngineLifecycleSnapshot,
  FerrumAssetApi,
  FerrumEngine,
  FerrumLifecycleApi,
  FerrumParticleApi,
  FerrumPhysicsApi,
  FerrumPhysicsBodyApi,
  FerrumPhysicsJointApi,
  FerrumPhysicsQueryApi,
  FerrumPhysicsRuntimeApi,
  FerrumSceneApi,
  FixedTimestepOptions,
  FrameHandler,
  FrameState,
  InputProvider,
  PhysicsAabbTileObstacleManifoldQuery,
  PhysicsAabbTileObstacleContactQuery,
  PhysicsAabbBodyShapeCastQuery,
  PhysicsAabbBodyQuery,
  PhysicsAabbTileObstacleShapeCastQuery,
  PhysicsBodyColliderOptions,
  PhysicsBodyColliderSnapshot,
  PhysicsBodyStateBufferSnapshot,
  PhysicsBodyContactQuery,
  PhysicsBodyManifoldQuery,
  PhysicsCapsuleBodyShapeCastQuery,
  PhysicsCapsuleBodyQuery,
  PhysicsCircleBodyShapeCastQuery,
  PhysicsCircleBodyQuery,
  PhysicsConvexPolygonBodyShapeCastQuery,
  PhysicsConvexPolygonBodyQuery,
  PhysicsConvexPolygonVertexBuffer,
  PhysicsColliderType,
  PhysicsCollisionLayer,
  PhysicsDebugOptions,
  PhysicsEntityHandle,
  PhysicsEntitySnapshot,
  PhysicsJointBaseOptions,
  PhysicsJointHandle,
  PhysicsJointSnapshot,
  PhysicsJointSpawnOptions,
  PhysicsJointType,
  PhysicsMaterialSnapshot,
  PhysicsNearestBodyHit,
  PhysicsNearestBodyQuery,
  PhysicsNearestTileObstacleHit,
  PhysicsNearestTileObstacleQuery,
  PhysicsOrientedBoxBodyQuery,
  PhysicsPointBodyQuery,
  PhysicsRaycastBodyQuery,
  PhysicsRaycastTileObstacleQuery,
  PhysicsFrameStats,
  PhysicsRigidBodyCollider,
  PhysicsRigidBodyMassProperties,
  PhysicsRigidBodyMaterial,
  PhysicsRigidBodySpawnOptions,
  PhysicsRigidBodyStepOptions,
  PhysicsRigidBodyStepStats,
  PhysicsRigidBodyTuning,
  PhysicsRigidBodyType,
  PhysicsSegmentCastBodyQuery,
  PhysicsSegmentCastTileObstacleQuery,
  PhysicsShapeCastMotionQuery,
  PhysicsTileShapeCastMotionQuery,
  PhysicsOrientedBoxBodyShapeCastQuery,
  ShooterSoundIds,
  ShooterTextureIds,
  TilemapNavigationPath,
  TilemapNavigationPathPoint,
  TilemapNavigationPathQuery,
  TilemapNavigationWaypoint,
  TilemapNavigationWaypointQuery,
  TilemapRectEditOptions,
  ViewportSnapshot,
  ViewportProvider,
} from "./createEngine";
export { applyShooterGameSpec, resolveShooterGameSpec } from "./gameSpec";
export { FerrumDiagnosticError, diagnosticReport, formatDiagnosticReport, isFerrumDiagnosticError } from "./diagnostics";
export type { DiagnosticCode, DiagnosticContext, DiagnosticKind, DiagnosticReport } from "./diagnostics";
export {
  compilePhysicsAuthoringDocument,
  isPhysicsAuthoringDocument,
  PHYSICS_AUTHORING_SCHEMA_VERSION,
  validatePhysicsAuthoringDocument,
} from "./physicsAuthoringSchema";
export type {
  CompilePhysicsAuthoringOptions,
  PhysicsAuthoringDocument,
  PhysicsEditorBodyMetadata,
  PhysicsEditorGizmoKind,
  PhysicsEditorJointMetadata,
  PhysicsEditorMetadata,
  PhysicsEditorPresetMetadata,
} from "./physicsAuthoringSchema";
export {
  capturePhysicsWorldSnapshot,
  createPhysicsReplayInputStream,
  hashPhysicsWorldSnapshot,
  PHYSICS_REPLAY_INPUT_STREAM_FORMAT,
  PHYSICS_REPLAY_INPUT_STREAM_VERSION,
  PHYSICS_WORLD_SNAPSHOT_FORMAT,
  PHYSICS_WORLD_SNAPSHOT_VERSION,
  restorePhysicsWorldSnapshot,
  runPhysicsReplayInputStream,
  verifyPhysicsReplayInputStreamRollback,
  verifyPhysicsReplayRollback,
} from "./physicsSnapshot";
export type {
  CapturePhysicsWorldSnapshotOptions,
  PhysicsReplayApplyForceEvent,
  PhysicsReplayApplyImpulseEvent,
  PhysicsReplayFrameSnapshot,
  PhysicsReplayInputEvent,
  PhysicsReplayInputEventBase,
  PhysicsReplayInputRollbackOptions,
  PhysicsReplayInputRollbackResult,
  PhysicsReplayInputRunOptions,
  PhysicsReplayInputRunResult,
  PhysicsReplayInputStream,
  PhysicsReplayRollbackOptions,
  PhysicsReplayRollbackResult,
  PhysicsReplaySetEnabledEvent,
  PhysicsReplaySetPositionEvent,
  PhysicsReplaySetVelocityEvent,
  PhysicsWorldRestoreResult,
  PhysicsWorldSnapshot,
  PhysicsWorldSnapshotBody,
  PhysicsWorldSnapshotCollider,
  PhysicsWorldSnapshotHashOptions,
  PhysicsWorldSnapshotJoint,
  RestorePhysicsWorldSnapshotOptions,
} from "./physicsSnapshot";
export {
  PHYSICS_REPLAY_WORKER_REQUEST_FORMAT,
  PHYSICS_REPLAY_WORKER_RESPONSE_FORMAT,
  PHYSICS_REPLAY_WORKER_VERSION,
  PhysicsReplayWorkerClient,
  createPhysicsReplayWorkerClient,
} from "./physicsReplayWorker";
export type {
  CreatePhysicsReplayWorkerClientOptions,
  PhysicsReplayWorkerError,
  PhysicsReplayWorkerPort,
  PhysicsReplayWorkerRequest,
  PhysicsReplayWorkerResponse,
  PhysicsReplayWorkerRunOptions,
  PhysicsReplayWorkerRunResult,
  PhysicsReplayWorkerTransferBenchmarkOptions,
  PhysicsReplayWorkerTransferBenchmarkResult,
  PhysicsReplayWorkerTransferBenchmarkSample,
} from "./physicsReplayWorker";
export {
  PHYSICS_BUILTIN_COLLISION_LAYERS,
  PHYSICS_COMMON_LAYER_PATTERN,
  PHYSICS_MATERIAL_PRESETS,
  clearPhysicsWorld,
  createCollider,
  createJoint,
  createPhysicsLayerMap,
  createPhysicsLayerSpec,
  createPhysicsWorldFromSpec,
  createRigidBody,
  createVehicleRig,
  physicsLayerMaskBits,
  physicsMaterial,
} from "./physicsAuthoring";
export type {
  PhysicsAuthoringContext,
  PhysicsAuthoringLayer,
  PhysicsColliderAuthoringOptions,
  PhysicsJointAuthoringOptions,
  PhysicsJointEndpoint,
  PhysicsLayerMapOptions,
  PhysicsLayerPattern,
  PhysicsLayerPatternEntry,
  PhysicsMaterialAuthoringInput,
  PhysicsMaterialPresetName,
  PhysicsRigidBodyAuthoringOptions,
  PhysicsVehicleRigAuthoringOptions,
  PhysicsVehicleRigResult,
  PhysicsVehicleWheelAuthoringOptions,
  PhysicsWorldApplyOptions,
  PhysicsWorldApplyResult,
  PhysicsWorldApplyWarning,
} from "./physicsAuthoring";
export { applyPhysicsSceneProfile } from "./physicsSceneIntegration";
export type {
  ApplyPhysicsSceneProfileOptions,
  PhysicsSceneProfileApplyResult,
  PhysicsSceneProfileId,
  PhysicsSceneProfileSpec,
} from "./physicsSceneIntegration";
export {
  PixelMaskTerrain,
  createPixelMaskTerrain,
  extractPixelMaskBoundaryChains,
  pixelMaskTerrainToTilemapLayer,
} from "./pixelMaskTerrain";
export type {
  PixelMaskTerrainAlphaPatch,
  PixelMaskTerrainBoundaryOptions,
  PixelMaskTerrainDirtyRect,
  PixelMaskTerrainLayerOptions,
  PixelMaskTerrainOptions,
  PixelMaskTerrainTextureUploadOptions,
} from "./pixelMaskTerrain";
export { PixelMaskTerrainRuntime, createPixelMaskTerrainRuntime } from "./pixelMaskTerrainRuntime";
export type {
  PixelMaskTerrainRuntimeOptions,
  PixelMaskTerrainRuntimePhysicsOptions,
  PixelMaskTerrainRuntimeSyncOptions,
  PixelMaskTerrainRuntimeSyncResult,
  PixelMaskTerrainRuntimeTextureOptions,
  PixelMaskTerrainTextureTarget,
} from "./pixelMaskTerrainRuntime";
export { extractTilemapBoundaryChains } from "./tilemapPhysics";
export type {
  TilemapBoundaryChain,
  TilemapBoundaryExtractionOptions,
  TilemapBoundaryExtractionResult,
} from "./tilemapPhysics";
export { DEFAULT_PHYSICS_MODE, resolvePhysicsMode, resolvePhysicsSpec } from "./physicsSpec";
export type {
  PhysicsBodySpec,
  PhysicsBoxColliderSpec,
  PhysicsCapsuleColliderSpec,
  PhysicsChainColliderSpec,
  PhysicsCircleColliderSpec,
  PhysicsColliderSpec,
  PhysicsConvexPolygonColliderSpec,
  PhysicsDebugSpec,
  PhysicsEdgeColliderSpec,
  PhysicsJointLimitSpec,
  PhysicsJointMotorSpec,
  PhysicsJointSpec,
  PhysicsLayerSpec,
  PhysicsMaterialSpec,
  PhysicsMode,
  PhysicsOrientedBoxColliderSpec,
  PhysicsSolverSpec,
  PhysicsSpec,
  PhysicsSpecBodyType,
  PhysicsSpecColliderShape,
  PhysicsSpecJointType,
  PhysicsSpecVector2,
  ResolvedPhysicsBodySpec,
  ResolvedPhysicsBoxColliderSpec,
  ResolvedPhysicsCapsuleColliderSpec,
  ResolvedPhysicsChainColliderSpec,
  ResolvedPhysicsCircleColliderSpec,
  ResolvedPhysicsColliderBaseSpec,
  ResolvedPhysicsColliderSpec,
  ResolvedPhysicsDebugSpec,
  ResolvedPhysicsEdgeColliderSpec,
  ResolvedPhysicsJointSpec,
  ResolvedPhysicsLayerSpec,
  ResolvedPhysicsMaterialSpec,
  ResolvedPhysicsOrientedBoxColliderSpec,
  ResolvedPhysicsSolverSpec,
  ResolvedPhysicsSpec,
  ResolvedPhysicsVector2,
  ResolvePhysicsSpecOptions,
} from "./physicsSpec";
export type {
  ApplyShooterGameSpecOptions,
  ResolveShooterGameSpecOptions,
  ResolvedShooterAtlasAnimation,
  ResolvedShooterAtlasAnimationState,
  ResolvedShooterAtlasFrame,
  ResolvedShooterGameSpec,
  ResolvedShooterPhysicsMaterial,
  ResolvedShooterPrefabAabbCollider,
  ResolvedShooterPrefabColliderBase,
  ResolvedShooterPrefabCollider,
  ResolvedShooterPrefabColliderVertex,
  ResolvedShooterWave,
  ShooterAtlasAnimationSpec,
  ShooterAtlasAnimationStateSpec,
  ShooterAudioEventPolicySpec,
  ShooterAudioSpec,
  ShooterAtlasFrameSpec,
  ShooterAtlasSpec,
  ShooterCameraPreset,
  ShooterCameraSpec,
  ShooterEnemyBehaviorPreset,
  ShooterEnemyOrbitSpec,
  ShooterEnemyPresetSpec,
  ShooterGameSpec,
  ShooterGameSpecTarget,
  ShooterPhysicsMaterialSpec,
  ShooterPrefabColliderSpec,
  ShooterPrefabColliderType,
  ShooterPrefabSpec,
  ShooterTileLayerSpec,
  ShooterTilemapSpec,
  ShooterTileSlopeSpec,
  ShooterTileSpec,
  ResolvedShooterTileDefinition,
  ResolvedShooterTileLayer,
  ResolvedShooterTileSlopeDefinition,
  ResolvedShooterTilemap,
  ShooterWaveSpec,
} from "./gameSpec";
export type {
  ParticleColor,
  ParticlePresetConfig,
  ParticleRangeInput,
  ParticleTextureRef,
  ParticleUvRect,
} from "./particlePreset";
export type {
  ParticleVfxEmitterConfig,
  ParticleVfxEmitterMode,
  ParticleVfxEmitterOptions,
  ParticleVfxEmitterSnapshot,
  ParticleVfxEmitterTarget,
  ParticleVfxPresetConfig,
  ParticleVfxPresetName,
  ResolvedParticleVfxEmitterConfig,
  ResolvedParticleVfxPresetConfig,
} from "./particleVfx";
export type { Renderer, RendererStats } from "./renderer";
export type { CreatedRenderer, CreateRendererOptions, RendererFallbackInfo } from "./createRenderer";
export { WebGL2Renderer } from "./webgl2Renderer";
export type { WebGL2RendererOptions } from "./webgl2Renderer";
export type { WebGPURendererOptions } from "./webgpuRenderer";
export type { PhysicsDebugLineCamera } from "./physicsDebugLineBatch";
export { BrowserPlatformHost } from "./browserPlatformHost";
export { WebGPURenderer } from "./webgpuRenderer";
export { TextureManager } from "./textureManager";
export { AudioManager } from "./audioManager";
export type {
  AudioBus,
  AudioManagerConfig,
  AudioManagerState,
  PlayBgmOptions,
  StopBgmOptions,
  SpatialAudioOptions,
} from "./audioManager";
export { AudioAssetLoader } from "./audioAssetLoader";
export { AssetLoader } from "./assetLoader";
export {
  buildDebugGizmoLineBuffer,
  buildDebugGizmoLines,
  debugGizmoLinesToBuffer,
} from "./debugGizmos";
export {
  assetManifestFingerprint,
  createAssetPreloadCachePolicy,
  invalidatePreloadedAssetCache,
  preloadAssetManifest,
  resolveAssetPreloadPlan,
} from "./assetPreload";
export { IndexedDbAssetCache } from "./indexedDbAssetCache";
export {
  importAsepriteAtlas,
  importAsepriteAtlasFrames,
  importLDtkGameSpec,
  importLDtkTilemap,
  importTiledGameSpec,
  importTiledTilemap,
} from "./assetPipeline";
export { DebugOverlay } from "./debugOverlay";
export { LoadingOverlay } from "./loadingOverlay";
export {
  evaluateRuntimeDiagnosticsSample,
  evaluateRuntimeProfilerBudget,
  RuntimeProfiler,
  runtimeDiagnosticsFrameSample,
} from "./runtimeProfiler";
export { UiOverlay } from "./uiOverlay";
export {
  HUD_THEME_PRESETS,
  createHudOverlayState,
  resolveHudTheme,
} from "./hudToolkit";
export {
  ACCESSIBILITY_CONTRAST_PALETTES,
  accessibilitySubtitlePanel,
  applyAccessibilityToCameraRigSpec,
  applyAccessibilityToScreenFadeSpec,
  readAccessibilityEnvironment,
  resolveAccessibilityContrastPalette,
  resolveAccessibilityHudTheme,
  resolveAccessibilityOptions,
} from "./accessibilityOptions";
export {
  CameraRigController,
  ScreenFadeTransition,
  clampCameraToBounds,
  fadePostProcessPass,
  resolveCameraRigSpec,
  resolvePostProcessPasses,
} from "./cameraPostProcessing";
export {
  CutsceneSequencePlayer,
  applyCutsceneSequenceEvent,
  resolveCutsceneSequenceSpec,
} from "./cutsceneSequence";
export {
  LocalizationBundle,
  layoutLocalizedText,
  loadFontLoadingPolicy,
  localizationLocaleChain,
  resolveFontLoadingPolicy,
  resolveLocalizationDocument,
} from "./localization";
export {
  LevelChunkStreamer,
  resolveLevelChunkManifest,
  resolveLevelStreamingPlan,
} from "./levelStreaming";
export {
  DialogueSession,
  QuestLog,
  captureDialogueQuestState,
  dialogueNodeToUiOverlayState,
  resolveDialogueGraph,
  resolveQuestDocument,
  restoreDialogueQuestState,
} from "./dialogueQuest";
export { TextureRegistry } from "./textureRegistry";
export { SoundRegistry } from "./soundRegistry";
export { SpriteBatch } from "./spriteBatch";
export { InputManager } from "./inputManager";
export {
  BREAKOUT_INPUT_ACTION_PROFILE,
  DEFAULT_INPUT_ACTION_PROFILE,
  INPUT_ACTION_PROFILES,
  PLATFORMER_INPUT_ACTION_PROFILE,
  resolveInputActionState,
  TOPDOWN_SHOOTER_INPUT_ACTION_PROFILE,
} from "./inputProfile";
export {
  applyVirtualControlStateToSnapshot,
  DEFAULT_VIRTUAL_CONTROL_BUTTONS,
  VirtualControls,
} from "./virtualControls";
export {
  DEFAULT_SPRITE_MATERIAL_PRESET,
  resolveSpriteMaterialPreset,
  SPRITE_MATERIAL_PRESETS,
  spriteMaterialPasses,
  spriteMaterialPassRequiresCommandCopy,
  writeSpriteMaterialPassCommands,
} from "./spriteMaterial";
export {
  PARTICLE_VFX_PRESETS,
  ParticleVfxEmitter,
  particleVfxPreset,
  resolveParticleVfxPresetConfig,
} from "./particleVfx";
export {
  deriveTileOccludersFromTilemapGrid,
  normalizeLightingScene,
} from "./lighting";
export {
  TEXTURE_ATLAS_PACK_FORMAT,
  TEXTURE_ATLAS_PACK_VERSION,
  generateTextureAtlasLayout,
  packTextureAtlas,
  textureAtlasDocumentToShooterAtlas,
} from "./textureAtlas";
export {
  SCREENSHOT_CAPTURE_SUMMARY_FORMAT,
  SCREENSHOT_CAPTURE_SUMMARY_VERSION,
  assertScreenshotCaptureSummary,
  compareScreenshotSummaries,
  resolveScreenshotCaptureSpec,
  summarizeScreenshotPixels,
} from "./screenshotCapture";
export type {
  AtlasSpriteInput,
  AtlasSpritePlacement,
  PackedTextureAtlasDocument,
  PackedTextureAtlasFrame,
  TextureAtlasLayout,
  TextureAtlasOptions,
  TextureAtlasPackInput,
  TextureAtlasPackOptions,
} from "./textureAtlas";
export type {
  ResolvedScreenshotCaptureSpec,
  ScreenshotCaptureSpec,
  ScreenshotColorSummary,
  ScreenshotComparisonReport,
  ScreenshotComparisonThreshold,
  ScreenshotPixelSummary,
} from "./screenshotCapture";
export {
  applyTileRules,
  bakeAnimatedTileLayer,
  resolveAnimatedTileFrame,
} from "./tilemapAuthoring";
export type { GamepadInputMapping, InputManagerOptions, InputSnapshot } from "./inputManager";
export type {
  InputActionBinding,
  InputActionProfile,
  InputActionProfileId,
  InputActionState,
  InputAxisBinding,
  InputDigitalControl,
  ResolveInputActionStateOptions,
} from "./inputProfile";
export type {
  VirtualButtonOptions,
  VirtualControlsOptions,
  VirtualControlsState,
  VirtualJoystickOptions,
} from "./virtualControls";
export type {
  ResolvedSpriteMaterialColorMix,
  ResolvedSpriteMaterialOutline,
  ResolvedSpriteMaterialPreset,
  SpriteMaterialBlendMode,
  SpriteMaterialColor,
  SpriteMaterialColorMix,
  SpriteMaterialOutlineDirections,
  SpriteMaterialOutlineOptions,
  SpriteMaterialPass,
  SpriteMaterialPreset,
  SpriteMaterialPresetInput,
  SpriteMaterialPresetName,
} from "./spriteMaterial";
export type {
  LightingColor3,
  LightingColor4,
  LightingDebugOptions,
  LightingShadowOptions,
  LightingScene2D,
  PointLight2D,
  ResolvedLightingDebugOptions,
  ResolvedLightingShadowOptions,
  ResolvedLightingScene2D,
  ResolvedPointLight2D,
  ShadowClipRect,
  ShadowProjectionOptions,
  TileOccluder2D,
  TileOccluderGridInput,
} from "./lighting";
export type { SpriteDrawOptions } from "./spriteBatch";
export type {
  AnimatedTileFrameSpec,
  AnimatedTileLayerOptions,
  AnimatedTileSpec,
  ApplyTileRulesOptions,
  TileRuleCellMatch,
  TileRuleGrid,
  TileRuleNeighborDirection,
  TileRuleNeighborMatch,
  TileRuleSpec,
} from "./tilemapAuthoring";
export type {
  DebugGizmoBoundsSpec,
  DebugGizmoCategory,
  DebugGizmoColor,
  DebugGizmoLine,
  DebugGizmoLineBufferResult,
  DebugGizmoOptions,
  DebugGizmoPathSpec,
  DebugGizmoPoint,
  DebugGizmoSceneSpec,
  DebugGizmoSpawnSpec,
  ResolvedDebugGizmoColor,
} from "./debugGizmos";
export type {
  AssetLoadProgress,
  AssetLoadProgressCallback,
  AssetManifest,
  LoadedAssets,
  SoundAssetManager,
  TextureAssetManager,
} from "./assetLoader";
export type {
  AssetPreloadCache,
  AssetPreloadCachePolicy,
  AssetPreloadEntry,
  AssetPreloadInvalidationResult,
  AssetPreloadKind,
  AssetPreloadPlan,
  CreateAssetPreloadCachePolicyOptions,
  InvalidatePreloadedAssetCacheOptions,
  PreloadAssetManifestOptions,
  PreloadedAssetManifest,
} from "./assetPreload";
export type {
  BinaryAssetCache,
  BinaryCacheSetOptions,
  IndexedDbAssetCacheOptions,
  JsonAssetCache,
  JsonCacheSetOptions,
} from "./indexedDbAssetCache";
export type {
  AsepriteAtlasFrameSizeSource,
  AsepriteAtlasImportOptions,
  AsepriteAtlasImportResult,
  LDtkEntityInstance,
  LDtkTilemapImportOptions,
  LDtkTilemapImportResult,
  LDtkTilesetFrameContext,
  TiledLayerCompressionContext,
  TiledLayerDataDecoder,
  TiledTilemapImportOptions,
  TiledTilemapImportResult,
  TiledTilesetFrameContext,
} from "./assetPipeline";
export type { TextureRegistryEntry } from "./textureRegistry";
export type { SoundRegistryEntry } from "./soundRegistry";
export type { DebugOverlayMetrics, DebugOverlayOptions } from "./debugOverlay";
export type {
  LoadingOverlayOptions,
  LoadingOverlayState,
  LoadingOverlayStatus,
} from "./loadingOverlay";
export type {
  RuntimeAssetLoadSample,
  RuntimeDiagnosticsBudget,
  RuntimeDiagnosticsFrameSample,
  RuntimeDiagnosticsReport,
  RuntimeDiagnosticsUnit,
  RuntimeDiagnosticsViolation,
  RuntimeProfilerOptions,
  RuntimeProfilerSnapshot,
} from "./runtimeProfiler";
export type {
  UiAction,
  UiDialog,
  UiOverlayActionEvent,
  UiOverlayActionTone,
  UiOverlayOptions,
  UiOverlayRegion,
  UiOverlayState,
  UiOverlayTone,
  UiPanel,
  UiMeter,
  UiTextLine,
} from "./uiOverlay";
export type {
  AccessibilityContrastColorRole,
  AccessibilityContrastPaletteName,
  AccessibilityContrastPaletteSpec,
  AccessibilityEnvironment,
  AccessibilityInputAssistSpec,
  AccessibilityMediaQueryListLike,
  AccessibilityMediaQuerySource,
  AccessibilityOptionsSpec,
  AccessibilityReducedMotionPreference,
  AccessibilitySubtitlePanelOptions,
  AccessibilitySubtitleSpec,
  ResolvedAccessibilityContrastPalette,
  ResolvedAccessibilityInputAssist,
  ResolvedAccessibilityOptions,
  ResolveAccessibilityOptionsOptions,
} from "./accessibilityOptions";
export type {
  CreateHudOverlayStateOptions,
  HudComponentBase,
  HudComponentSpec,
  HudCounterSpec,
  HudMessageSpec,
  HudMeterSpec,
  HudPromptSpec,
  HudThemeInput,
  HudThemePresetName,
  HudThemeTokens,
  ResolvedHudThemeTokens,
} from "./hudToolkit";
export type {
  CameraBounds,
  CameraDeadZone,
  CameraPoint,
  CameraRigSnapshot,
  CameraRigSpec,
  CameraRigStepOptions,
  CameraViewport,
  BloomPostProcessPassInput,
  CrtPostProcessPassInput,
  FadePostProcessPassInput,
  GlitchPostProcessPassInput,
  PostProcessColor,
  PostProcessPassInput,
  PostProcessPassKind,
  PostProcessingConfigInput,
  PostProcessStackInput,
  VignettePostProcessPassInput,
  ResolvedCameraBounds,
  ResolvedCameraDeadZone,
  ResolvedCameraRigSpec,
  ResolvedBloomPostProcessPass,
  ResolvedCrtPostProcessPass,
  ResolvedFadePostProcessPass,
  ResolvedGlitchPostProcessPass,
  ResolvedPostProcessColor,
  ResolvedPostProcessPass,
  ResolvedVignettePostProcessPass,
  ResolveCameraRigOptions,
  ResolvePostProcessOptions,
  ScreenFadeTransitionSnapshot,
  ScreenFadeTransitionSpec,
} from "./cameraPostProcessing";
export type {
  CutsceneAudioAction,
  CutsceneAudioBus,
  CutsceneAudioCommandSpec,
  CutsceneCameraCommandSpec,
  CutsceneCommandBaseSpec,
  CutsceneDialogueCommandSpec,
  CutsceneSequenceCommandKind,
  CutsceneSequenceCommandSpec,
  CutsceneSequenceEasing,
  CutsceneSequenceEvent,
  CutsceneSequencePlayerSnapshot,
  CutsceneSequenceSpec,
  CutsceneSequenceTarget,
  CutsceneSequenceUpdateOptions,
  CutsceneSequenceUpdateResult,
  CutsceneWaitCommandSpec,
  ResolveCutsceneSequenceOptions,
  ResolvedCutsceneAudioCommand,
  ResolvedCutsceneCameraCommand,
  ResolvedCutsceneCommandBase,
  ResolvedCutsceneDialogueCommand,
  ResolvedCutsceneSequenceCommand,
  ResolvedCutsceneSequenceSpec,
  ResolvedCutsceneWaitCommand,
} from "./cutsceneSequence";
export type {
  BitmapFontPolicySpec,
  FontDisplayPolicy,
  FontFaceSetLike,
  FontLoadingPolicySpec,
  LoadFontPolicyResult,
  LocalizationDocumentSpec,
  LocalizationLocaleSpec,
  LocalizationPlaceholderValue,
  LocalizationStringEntrySpec,
  LocalizationStringSpec,
  LocalizeOptions,
  LocalizedTextResult,
  MissingLocalizationBehavior,
  ResolvedBitmapFontPolicy,
  ResolvedFontLoadingPolicy,
  ResolvedLocalizationDocument,
  ResolvedLocalizationLocale,
  ResolvedLocalizationString,
  ResolvedWebFontPolicy,
  ResolveLocalizationOptions,
  TextDirection,
  TextLayoutLine,
  TextLayoutOptions,
  TextLayoutResult,
  WebFontPolicySpec,
} from "./localization";
export type {
  LevelChunkBounds,
  LevelChunkManifestSpec,
  LevelChunkSpec,
  LevelChunkStreamerSnapshot,
  LevelStreamingAssetLifetimePolicy,
  LevelStreamingOrigin,
  LevelStreamingPlan,
  LevelStreamingPlanOptions,
  LevelStreamingViewport,
  LevelTilemapChunkSpec,
  ResolveLevelChunkManifestOptions,
  ResolvedLevelChunk,
  ResolvedLevelChunkManifest,
  ResolvedLevelTilemapChunk,
} from "./levelStreaming";
export type {
  DialogueChoiceResult,
  DialogueChoiceSpec,
  DialogueGraphSpec,
  DialogueNodeSpec,
  DialogueQuestStateSnapshot,
  DialogueSessionSnapshot,
  DialogueUiOptions,
  QuestDocumentSpec,
  QuestLogSnapshot,
  QuestObjectiveSpec,
  QuestProgressSnapshot,
  QuestSpec,
  QuestStageSpec,
  QuestStatus,
  QuestUpdateAction,
  QuestUpdateSpec,
  ResolvedDialogueChoice,
  ResolvedDialogueGraph,
  ResolvedDialogueNode,
  ResolvedQuest,
  ResolvedQuestDocument,
  ResolvedQuestObjective,
  ResolvedQuestStage,
  ResolvedQuestUpdate,
  ResolveDialogueQuestOptions,
  RestoreDialogueQuestStateOptions,
} from "./dialogueQuest";
export type {
  AudioEventBufferView,
  AudioEventView,
  CollisionEventBufferView,
  CollisionEventKind,
  CollisionEventView,
  PhysicsBodyContactHit,
  PhysicsBodyContactHitBufferView,
  PhysicsBodyManifoldHit,
  PhysicsBodyManifoldHitBufferView,
  PhysicsBodyQueryHit,
  PhysicsDebugLineBufferView,
  PhysicsDebugLineView,
  PhysicsQueryHitBufferView,
  PhysicsRaycastBodyHit,
  PhysicsRaycastHitBufferView,
  PhysicsRigidContactImpulseHit,
  PhysicsRigidContactImpulseHitBufferView,
  PhysicsShapeCastBodyHit,
  PhysicsShapeCastHitBufferView,
  PhysicsTileContactHit,
  PhysicsTileContactHitBufferView,
  PhysicsTileManifoldHit,
  PhysicsTileManifoldHitBufferView,
  PhysicsTileRaycastHit,
  PhysicsTileRaycastHitBufferView,
  PhysicsTileShapeCastHit,
  PhysicsTileShapeCastHitBufferView,
  RenderCommandBufferView,
  RenderCommandView,
} from "./wasmBridge";
export {
  decodeCollisionEvents,
  decodePhysicsDebugLines,
  decodePhysicsBodyContactHits,
  decodePhysicsBodyManifoldHits,
  decodePhysicsRigidContactImpulseHits,
  decodePhysicsQueryHits,
  decodePhysicsRaycastHits,
  decodePhysicsShapeCastHits,
  decodePhysicsTileContactHits,
  decodePhysicsTileManifoldHits,
  decodePhysicsTileRaycastHits,
  decodePhysicsTileShapeCastHits,
  decodeRenderCommands,
} from "./wasmBridge";
