import { deepEqual } from "node:assert/strict";
import { test } from "node:test";
import {
  GAMEPLAY_ACTION_FAILURE_BLOCKED_PLACEMENT,
  GAMEPLAY_ACTION_FAILURE_COOLING_DOWN,
  GAMEPLAY_ACTION_FAILURE_MISSING_ACTION_BINDING,
  GAMEPLAY_ACTION_FAILURE_MISSING_ACTION_TARGET,
  GAMEPLAY_ACTION_FAILURE_MAX_REASON_CODE,
  GAMEPLAY_ACTION_FAILURE_PATTERN_MISMATCH,
  GAMEPLAY_ACTION_FAILURE_SPAWN_QUEUE_FULL,
  GAMEPLAY_ACTION_FAILURE_UNSUPPORTED_AIM_SOURCE,
  GAMEPLAY_ACTION_FAILURE_UNSUPPORTED_COLLISION_TARGET,
  GAMEPLAY_EVENT_KIND_COLLISION_DAMAGE,
  GAMEPLAY_EVENT_KIND_COLLISION_DESPAWN,
  GAMEPLAY_EVENT_KIND_BEHAVIOR_STATE_CHANGED,
  GAMEPLAY_EVENT_KIND_INTERACTION,
  GAMEPLAY_EVENT_KIND_PREFAB_SPAWNED,
  GAMEPLAY_EVENT_KIND_ACTION_FAILED,
  GAMEPLAY_EVENT_KIND_TIMER,
  GAMEPLAY_EVENT_KIND_PICKUP_COLLECTED,
  GAMEPLAY_EVENT_KIND_TILE_IMPACT,
  GAMEPLAY_EVENT_KIND_FACTION_DAMAGE_DENIED,
  GAMEPLAY_EVENT_FLAG_CONSUMED_THIS_FRAME,
  GAMEPLAY_EVENT_FLAG_ONCE,
  GAMEPLAY_EVENT_FLAG_TARGET_REMOVED,
  GAMEPLAY_EVENT_FLAG_TILE_IMPACT_BOUNCED,
  GAMEPLAY_EVENT_TILE_IMPACT_NORMAL_NEGATIVE_X,
  GAMEPLAY_EVENT_TILE_IMPACT_NORMAL_SHIFT,
  decodeGameplayEvents,
  gameplayEventKind,
} from "../src/gameplayEventDecoder.js";

test("gameplay event kind constants match the Rust ABI codes", () => {
  deepEqual([
    [GAMEPLAY_EVENT_KIND_INTERACTION, gameplayEventKind(GAMEPLAY_EVENT_KIND_INTERACTION)],
    [GAMEPLAY_EVENT_KIND_COLLISION_DAMAGE, gameplayEventKind(GAMEPLAY_EVENT_KIND_COLLISION_DAMAGE)],
    [GAMEPLAY_EVENT_KIND_COLLISION_DESPAWN, gameplayEventKind(GAMEPLAY_EVENT_KIND_COLLISION_DESPAWN)],
    [GAMEPLAY_EVENT_KIND_BEHAVIOR_STATE_CHANGED, gameplayEventKind(GAMEPLAY_EVENT_KIND_BEHAVIOR_STATE_CHANGED)],
    [GAMEPLAY_EVENT_KIND_PREFAB_SPAWNED, gameplayEventKind(GAMEPLAY_EVENT_KIND_PREFAB_SPAWNED)],
    [GAMEPLAY_EVENT_KIND_ACTION_FAILED, gameplayEventKind(GAMEPLAY_EVENT_KIND_ACTION_FAILED)],
    [GAMEPLAY_EVENT_KIND_TIMER, gameplayEventKind(GAMEPLAY_EVENT_KIND_TIMER)],
    [GAMEPLAY_EVENT_KIND_PICKUP_COLLECTED, gameplayEventKind(GAMEPLAY_EVENT_KIND_PICKUP_COLLECTED)],
    [GAMEPLAY_EVENT_KIND_TILE_IMPACT, gameplayEventKind(GAMEPLAY_EVENT_KIND_TILE_IMPACT)],
    [GAMEPLAY_EVENT_KIND_FACTION_DAMAGE_DENIED, gameplayEventKind(GAMEPLAY_EVENT_KIND_FACTION_DAMAGE_DENIED)],
  ], [
    [1, "interaction"],
    [2, "collisionDamage"],
    [3, "collisionDespawn"],
    [4, "behaviorStateChanged"],
    [5, "prefabSpawned"],
    [6, "actionFailed"],
    [7, "timer"],
    [8, "pickupCollected"],
    [9, "tileImpact"],
    [10, "factionDamageDenied"],
  ]);
});

test("gameplay action failure constants match the Rust ABI codes", () => {
  deepEqual([
    GAMEPLAY_ACTION_FAILURE_SPAWN_QUEUE_FULL,
    GAMEPLAY_ACTION_FAILURE_PATTERN_MISMATCH,
    GAMEPLAY_ACTION_FAILURE_BLOCKED_PLACEMENT,
    GAMEPLAY_ACTION_FAILURE_MISSING_ACTION_BINDING,
    GAMEPLAY_ACTION_FAILURE_COOLING_DOWN,
    GAMEPLAY_ACTION_FAILURE_UNSUPPORTED_AIM_SOURCE,
    GAMEPLAY_ACTION_FAILURE_MISSING_ACTION_TARGET,
    GAMEPLAY_ACTION_FAILURE_UNSUPPORTED_COLLISION_TARGET,
    GAMEPLAY_ACTION_FAILURE_MAX_REASON_CODE,
  ], [
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    12,
  ]);
});

test("decodeGameplayEvents parses packed gameplay event u32s", () => {
  const events = decodeGameplayEvents({
    buffer: new Uint32Array([
      1,
      3,
      0,
      9,
      2,
      7,
      GAMEPLAY_EVENT_FLAG_ONCE | GAMEPLAY_EVENT_FLAG_CONSUMED_THIS_FRAME,
      0,
      99,
      4,
      1,
      12,
      3,
      22,
      0,
      123,
      2,
      4,
      1,
      12,
      3,
      0,
      GAMEPLAY_EVENT_FLAG_TARGET_REMOVED,
      0x3f800000,
      4,
      12,
      3,
      12,
      3,
      2,
      0,
      1,
      5,
      20,
      1,
      7,
      0,
      1,
      0,
      11,
      6,
      7,
      0,
      7,
      0,
      11,
      0,
      GAMEPLAY_ACTION_FAILURE_SPAWN_QUEUE_FULL,
      7,
      8,
      0,
      8,
      0,
      9,
      0,
      0x3e800000,
      8,
      10,
      1,
      0,
      0,
      1,
      GAMEPLAY_EVENT_FLAG_TARGET_REMOVED,
      3,
      GAMEPLAY_EVENT_KIND_FACTION_DAMAGE_DENIED,
      4,
      1,
      12,
      3,
      2,
      0,
      1,
      9,
      11,
      0,
      11,
      0,
      2,
      GAMEPLAY_EVENT_FLAG_TILE_IMPACT_BOUNCED | (GAMEPLAY_EVENT_TILE_IMPACT_NORMAL_NEGATIVE_X << GAMEPLAY_EVENT_TILE_IMPACT_NORMAL_SHIFT),
      (1 << 24) | 4,
    ]),
    eventCount: 10,
    u32sPerEvent: 8,
  });

  deepEqual(events, [
    {
      kind: "interaction",
      kindCode: 1,
      actorId: 3,
      actorGeneration: 0,
      sourceId: 9,
      sourceGeneration: 2,
      tokenId: 7,
      flags: GAMEPLAY_EVENT_FLAG_ONCE | GAMEPLAY_EVENT_FLAG_CONSUMED_THIS_FRAME,
      payloadBits: 0,
      once: true,
      consumedThisFrame: true,
      targetRemoved: false,
    },
    {
      kind: "unknown",
      kindCode: 99,
      actorId: 4,
      actorGeneration: 1,
      sourceId: 12,
      sourceGeneration: 3,
      tokenId: 22,
      flags: 0,
      payloadBits: 123,
      once: false,
      consumedThisFrame: false,
      targetRemoved: false,
    },
    {
      kind: "collisionDamage",
      kindCode: 2,
      actorId: 4,
      actorGeneration: 1,
      sourceId: 12,
      sourceGeneration: 3,
      tokenId: 0,
      flags: GAMEPLAY_EVENT_FLAG_TARGET_REMOVED,
      payloadBits: 0x3f800000,
      once: false,
      consumedThisFrame: false,
      targetRemoved: true,
    },
    {
      kind: "behaviorStateChanged",
      kindCode: 4,
      actorId: 12,
      actorGeneration: 3,
      sourceId: 12,
      sourceGeneration: 3,
      tokenId: 2,
      flags: 0,
      payloadBits: 1,
      once: false,
      consumedThisFrame: false,
      targetRemoved: false,
    },
    {
      kind: "prefabSpawned",
      kindCode: 5,
      actorId: 20,
      actorGeneration: 1,
      sourceId: 7,
      sourceGeneration: 0,
      tokenId: 1,
      flags: 0,
      payloadBits: 11,
      once: false,
      consumedThisFrame: false,
      targetRemoved: false,
    },
    {
      kind: "actionFailed",
      kindCode: 6,
      actorId: 7,
      actorGeneration: 0,
      sourceId: 7,
      sourceGeneration: 0,
      tokenId: 11,
      flags: 0,
      payloadBits: GAMEPLAY_ACTION_FAILURE_SPAWN_QUEUE_FULL,
      once: false,
      consumedThisFrame: false,
      targetRemoved: false,
    },
    {
      kind: "timer",
      kindCode: 7,
      actorId: 8,
      actorGeneration: 0,
      sourceId: 8,
      sourceGeneration: 0,
      tokenId: 9,
      flags: 0,
      payloadBits: 0x3e800000,
      once: false,
      consumedThisFrame: false,
      targetRemoved: false,
    },
    {
      kind: "pickupCollected",
      kindCode: 8,
      actorId: 10,
      actorGeneration: 1,
      sourceId: 0,
      sourceGeneration: 0,
      tokenId: 1,
      flags: GAMEPLAY_EVENT_FLAG_TARGET_REMOVED,
      payloadBits: 3,
      once: false,
      consumedThisFrame: false,
      targetRemoved: true,
    },
    {
      kind: "factionDamageDenied",
      kindCode: GAMEPLAY_EVENT_KIND_FACTION_DAMAGE_DENIED,
      actorId: 4,
      actorGeneration: 1,
      sourceId: 12,
      sourceGeneration: 3,
      tokenId: 2,
      flags: 0,
      payloadBits: 1,
      once: false,
      consumedThisFrame: false,
      targetRemoved: false,
    },
    {
      kind: "tileImpact",
      kindCode: 9,
      actorId: 11,
      actorGeneration: 0,
      sourceId: 11,
      sourceGeneration: 0,
      tokenId: 2,
      flags: GAMEPLAY_EVENT_FLAG_TILE_IMPACT_BOUNCED | (GAMEPLAY_EVENT_TILE_IMPACT_NORMAL_NEGATIVE_X << GAMEPLAY_EVENT_TILE_IMPACT_NORMAL_SHIFT),
      payloadBits: (1 << 24) | 4,
      once: false,
      consumedThisFrame: false,
      targetRemoved: false,
    },
  ]);
});
