export { equal } from "node:assert/strict";
export { test } from "node:test";
export {
  importAsepriteAtlas,
  importAsepriteAtlasFrames,
  importLDtkGameSpec,
  importLDtkTilemap,
  importTiledGameSpec,
  importTiledTilemap,
} from "../src/assetPipeline.js";
export {
  AnimationTimelinePlayer,
  animationTimelineFrameAt,
  resolveAnimationTimelineSpec,
} from "../src/animationTimeline.js";
export {
  applySceneCompositionFragment,
  instantiateSceneFragment,
  resolveSceneCompositionSpec,
} from "../src/sceneComposition.js";
export {
  applyBehaviorRecipes,
  behaviorRecipeCommandsForEntity,
  resolveBehaviorRecipeDocument,
} from "../src/behaviorRecipes.js";
export {
  BEHAVIOR_STATE_MACHINE_RUNTIME_MAX_TRANSITIONS,
  applyBehaviorStateMachineStateCommands,
  behaviorStateMachineBehaviorProfilesForState,
  behaviorStateMachineCommandsForState,
  compareBehaviorStateMachineReplay,
  createBehaviorStateMachineCurrentStateCommandPlan,
  createBehaviorStateMachineRuntimeInstallPlan,
  createBehaviorStateMachineStateCommandPlan,
  installBehaviorStateMachineRuntime,
  preflightBehaviorStateMachineStateCommands,
  runBehaviorStateMachineReplay,
  resolveBehaviorStateMachineDocument,
} from "../src/behaviorStateMachine.js";
export {
  GAMEPLAY_BEHAVIOR_BINDING_PROP,
  applyGameplayBehaviorCommands,
  bindSceneBehaviorRecipes,
  createGameplayBehaviorRuntimeTarget,
  dryRunSceneBehaviorRecipes,
  resolveGameplayBehaviorRuntimeIds,
} from "../src/gameplayAuthoring.js";
export {
  applyGameplayEventActions,
  gameplayActionFailureReasonForCode,
  gameplayEventActionMetadataForCommands,
  gameplayActionsForEvents,
  gameplayTileImpactForCode,
  gameplayTileImpactNormalForFlags,
  unpackTileImpactLayerIndex,
  unpackTileImpactTileIndex,
} from "../src/gameplayEventActions.js";
export {
  gameplayActionDiagnosticReports,
  suggestionForActionFailureReason,
} from "../src/gameplayActionDiagnostics.js";
export {
  gameplaySpawnDiagnosticReports,
  suggestionForSpawnDiagnosticMetric,
} from "../src/gameplaySpawnDiagnostics.js";
export {
  assetManifestFingerprint,
  createAssetPreloadCachePolicy,
  invalidatePreloadedAssetCache,
  preloadAssetManifest,
  resolveAssetPreloadPlan,
} from "../src/assetPreload.js";
export { IndexedDbAssetCache } from "../src/indexedDbAssetCache.js";
export { decodeCollisionEvents } from "../src/collisionEventDecoder.js";
export {
  GAMEPLAY_EVENT_FLAG_TILE_IMPACT_BOUNCED,
  GAMEPLAY_EVENT_FLAG_TILE_IMPACT_IDENTITY_TRUNCATED,
  GAMEPLAY_EVENT_KIND_FACTION_DAMAGE_DENIED,
  GAMEPLAY_EVENT_KIND_TILE_IMPACT,
  GAMEPLAY_EVENT_TILE_IMPACT_LAYER_MASK,
  GAMEPLAY_EVENT_TILE_IMPACT_LAYER_SHIFT,
  GAMEPLAY_EVENT_TILE_IMPACT_NORMAL_MASK,
  GAMEPLAY_EVENT_TILE_IMPACT_NORMAL_NEGATIVE_X,
  GAMEPLAY_EVENT_TILE_IMPACT_NORMAL_NEGATIVE_Y,
  GAMEPLAY_EVENT_TILE_IMPACT_NORMAL_NONE,
  GAMEPLAY_EVENT_TILE_IMPACT_NORMAL_POSITIVE_X,
  GAMEPLAY_EVENT_TILE_IMPACT_NORMAL_POSITIVE_Y,
  GAMEPLAY_EVENT_TILE_IMPACT_NORMAL_SHIFT,
  GAMEPLAY_EVENT_TILE_IMPACT_TILE_MASK,
  decodeGameplayEvents,
} from "../src/gameplayEventDecoder.js";
export { decodePhysicsDebugLines } from "../src/physicsDebugLineDecoder.js";
export {
  buildDebugGizmoLineBuffer,
  buildDebugGizmoLines,
  debugGizmoLinesToBuffer,
} from "../src/debugGizmos.js";
export {
  decodePhysicsBodyContactHits,
  decodePhysicsBodyManifoldHits,
  decodePhysicsQueryHits,
  decodePhysicsRaycastHits,
  decodePhysicsRigidContactImpulseHits,
  decodePhysicsShapeCastHits,
  decodePhysicsTileContactHits,
  decodePhysicsTileManifoldHits,
  decodePhysicsTileRaycastHits,
  decodePhysicsTileShapeCastHits,
} from "../src/physicsQueryDecoder.js";
export { resolvePhysicsSpec } from "../src/physicsSpec.js";
export {
  createCollider,
  createJoint,
  createPhysicsLayerMap,
  createPhysicsLayerSpec,
  createPhysicsWorldFromSpec,
  createRigidBody,
  physicsMaterial,
} from "../src/physicsAuthoring.js";
export { applyPhysicsSceneProfile } from "../src/physicsSceneIntegration.js";
export {
  createPixelMaskTerrain,
  extractPixelMaskBoundaryChains,
} from "../src/pixelMaskTerrain.js";
export {
  applyTileRules,
  bakeAnimatedTileLayer,
  resolveAnimatedTileFrame,
} from "../src/tilemapAuthoring.js";
export {
  BREAKOUT_INPUT_ACTION_PROFILE,
  DEFAULT_INPUT_ACTION_PROFILE,
  INPUT_ACTION_PROFILES,
  PLATFORMER_INPUT_ACTION_PROFILE,
  resolveInputActionState,
  TOPDOWN_SHOOTER_INPUT_ACTION_PROFILE,
} from "../src/inputProfile.js";
export {
  applyVirtualControlStateToSnapshot,
  DEFAULT_VIRTUAL_CONTROL_BUTTONS,
  VirtualControls,
} from "../src/virtualControls.js";
export {
  resolveSpriteMaterialPreset,
  SPRITE_MATERIAL_PRESETS,
  spriteMaterialPasses,
} from "../src/spriteMaterial.js";
export {
  PARTICLE_VFX_PRESETS,
  ParticleVfxEmitter,
  particleVfxPreset,
  resolveParticleVfxPresetConfig,
} from "../src/particleVfx.js";
export {
  deriveHd2dTileOccludersFromTilemapGrid,
  deriveTileOccludersFromTilemapGrid,
  normalizeLightingScene,
} from "../src/lighting.js";
export {
  captureGameStateSnapshot,
  GAME_STATE_SNAPSHOT_FORMAT,
  GAME_STATE_SNAPSHOT_VERSION,
  hashGameStateSnapshot,
  loadGameStateSnapshotFromStorage,
  parseGameStateSnapshot,
  restoreGameStateSnapshot,
  saveGameStateSnapshotToStorage,
  stringifyGameStateSnapshot,
} from "../src/gameStateSnapshot.js";
export {
  compareGameplayReplayRuns,
  createGameplayReplayRun,
  GAMEPLAY_REPLAY_RUN_FORMAT,
  GAMEPLAY_REPLAY_RUN_VERSION,
  hashGameplayReplayRun,
} from "../src/gameplayReplay.js";
export { createPixelMaskTerrainRuntime } from "../src/pixelMaskTerrainRuntime.js";
export {
  createPhysicsReplayInputStream,
  PHYSICS_WORLD_SNAPSHOT_FORMAT,
} from "../src/physicsSnapshot.js";
export {
  PHYSICS_REPLAY_WORKER_REQUEST_FORMAT,
  createPhysicsReplayWorkerClient,
} from "../src/physicsReplayWorker.js";
export {
  PHYSICS_BODY_STATE_BUFFER_FORMAT,
  PHYSICS_BODY_STATE_FLOATS_PER_BODY,
  PHYSICS_BODY_STATE_U32S_PER_BODY,
  createPhysicsBodyStateBufferSnapshot,
} from "../src/physicsBodyStateBuffer.js";
export {
  evaluateRuntimeProfilerBudget,
  RuntimeProfiler,
  runtimeDiagnosticsFrameSample,
} from "../src/runtimeProfiler.js";
export { LoadingOverlay } from "../src/loadingOverlay.js";
export {
  HUD_THEME_PRESETS,
  createHudOverlayState,
  resolveHudTheme,
} from "../src/hudToolkit.js";
export {
  ACCESSIBILITY_CONTRAST_PALETTES,
  accessibilitySubtitlePanel,
  applyAccessibilityToCameraRigSpec,
  applyAccessibilityToScreenFadeSpec,
  readAccessibilityEnvironment,
  resolveAccessibilityContrastPalette,
  resolveAccessibilityHudTheme,
  resolveAccessibilityOptions,
} from "../src/accessibilityOptions.js";
export {
  CameraRigController,
  ScreenFadeTransition,
  clampCameraToBounds,
  fadePostProcessPass,
  resolveCameraRigSpec,
  resolvePostProcessPasses,
} from "../src/cameraPostProcessing.js";
export {
  CutsceneSequencePlayer,
  applyCutsceneSequenceEvent,
  resolveCutsceneSequenceSpec,
} from "../src/cutsceneSequence.js";
export {
  LocalizationBundle,
  layoutLocalizedText,
  loadFontLoadingPolicy,
  localizationLocaleChain,
  resolveFontLoadingPolicy,
  resolveLocalizationDocument,
} from "../src/localization.js";
export {
  LevelChunkStreamer,
  resolveLevelChunkManifest,
  resolveLevelStreamingPlan,
} from "../src/levelStreaming.js";
export {
  DialogueSession,
  QuestLog,
  captureDialogueQuestState,
  dialogueNodeToUiOverlayState,
  resolveDialogueGraph,
  resolveQuestDocument,
  restoreDialogueQuestState,
} from "../src/dialogueQuest.js";
export {
  TEXTURE_ATLAS_PACK_FORMAT,
  packTextureAtlas,
  textureAtlasDocumentToShooterAtlas,
} from "../src/textureAtlas.js";
export {
  SCREENSHOT_CAPTURE_SUMMARY_FORMAT,
  SCREENSHOT_CAPTURE_SUMMARY_VERSION,
  assertScreenshotCaptureSummary,
  compareScreenshotSummaries,
  resolveScreenshotCaptureSpec,
  summarizeScreenshotPixels,
} from "../src/screenshotCapture.js";

import type {
  BuiltInShooterStateSnapshot,
  GameStateSceneSnapshot,
  GameStateSnapshot,
  GameStateSnapshotRestoreResult,
  GameplayReplayComparison,
  GameplayReplayFrameSnapshot,
  GameplayReplayRun,
  GameplayReplaySnapshotDiff,
} from "../src/index.js";

export type {
  AsepriteAtlasImportOptions,
  AsepriteAtlasImportResult,
  AnimatedTileFrameSpec,
  AnimatedTileLayerOptions,
  AnimatedTileSpec,
  ApplyTileRulesOptions,
  AssetPreloadCache,
  AssetPreloadCachePolicy,
  AssetPreloadEntry,
  AssetPreloadInvalidationResult,
  AssetPreloadPlan,
  AssetManifest,
  AnimationTimelineEmittedEvent,
  AnimationTimelineEventPayload,
  AnimationTimelineEventSpec,
  AnimationTimelineFrameRef,
  AnimationTimelinePlayerSnapshot,
  AnimationTimelineSpec,
  AnimationTimelineStateSpec,
  AnimationTimelineTransitionSpec,
  AnimationTimelineUpdateOptions,
  AnimationTimelineUpdateResult,
  ApplyBehaviorRecipesOptions,
  ApplyBehaviorStateMachineStateCommandsOptions,
  ApplyGameplayBehaviorCommandsOptions,
  ApplySceneCompositionOptions,
  AudioAssetLoader,
  AudioBus,
  AudioBusConfig,
  AudioManagerConfig,
  AudioManagerState,
  PlayBgmOptions,
  StopBgmOptions,
  SpatialAudioOptions,
  AtlasSpriteInput,
  AtlasSpritePlacement,
  PackedTextureAtlasDocument,
  PackedTextureAtlasFrame,
  ResolvedScreenshotCaptureSpec,
  ScreenshotCaptureSpec,
  ScreenshotColorSummary,
  ScreenshotComparisonReport,
  ScreenshotComparisonThreshold,
  ScreenshotPixelSummary,
  TextureAtlasLayout,
  TextureAtlasOptions,
  TextureAtlasPackInput,
  TextureAtlasPackOptions,
  BinaryAssetCache,
  BinaryCacheSetOptions,
  BehaviorRecipeApplyResult,
  BehaviorRecipeActionAim,
  BehaviorRecipeCommand,
  BehaviorRecipeCommandBase,
  BehaviorRecipeCommandOptions,
  BehaviorRecipeDamageTarget,
  BehaviorRecipeDocumentSpec,
  BehaviorRecipeEntrySpec,
  BehaviorRecipeEntitySpec,
  BehaviorRecipeFaction,
  BehaviorRecipeHealthZeroAction,
  BehaviorRecipeKind,
  BehaviorRecipeProjectileCollisionTarget,
  BehaviorRecipeProjectileTileImpact,
  BehaviorRecipeReferenceSpec,
  BehaviorRecipeRuntimeTarget,
  BehaviorRecipeSpec,
  BehaviorStateMachineBehaviorBinding,
  BehaviorStateMachineCommandOptions,
  BehaviorStateMachineDocumentSpec,
  BehaviorStateMachineGameplayEventKind,
  BehaviorStateMachineReplayComparison,
  BehaviorStateMachineReplayEventMatch,
  BehaviorStateMachineReplayFrame,
  BehaviorStateMachineReplayInput,
  BehaviorStateMachineReplayOptions,
  BehaviorStateMachineReplayResult,
  BehaviorStateMachineReplayStep,
  BehaviorStateMachineRuntimeEngine,
  BehaviorStateMachineRuntimeInstallOptions,
  BehaviorStateMachineRuntimeInstallPlan,
  BehaviorStateMachineRuntimeInstallResult,
  BehaviorStateMachineRuntimeStateQueryEngine,
  BehaviorStateMachineRuntimeStateId,
  BehaviorStateMachineRuntimeTransitionInstall,
  BehaviorStateMachineStateCommandApplyResult,
  BehaviorStateMachineStateCommandApplyMode,
  BehaviorStateMachineStateCommandOptions,
  BehaviorStateMachineStateCommandPlan,
  BehaviorStateMachineStateCommandPreflightResult,
  BehaviorStateMachineSpec,
  BehaviorStateMachineStateSpec,
  BehaviorStateMachineTransitionPredicateSpec,
  BehaviorStateMachineTransitionSpec,
  BehaviorStateMachineTriggerKind,
  BoundBehaviorRecipeCommand,
  BuiltInShooterStateSnapshot,
  ChaseBehaviorRecipeSpec,
  ConfigureChaseBehaviorCommand,
  ConfigureCollisionDespawnBehaviorCommand,
  ConfigureCollisionPickupBehaviorCommand,
  ConfigureCollisionParticleBehaviorCommand,
  ConfigureDamageBehaviorCommand,
  ConfigureDashActionBehaviorCommand,
  ConfigureFactionBehaviorCommand,
  ConfigureHealthBehaviorCommand,
  ConfigureInteractionBehaviorCommand,
  ConfigureLifetimeBehaviorCommand,
  ConfigureMeleeActionBehaviorCommand,
  ConfigurePickupBehaviorCommand,
  ConfigureProjectileActionBehaviorCommand,
  ConfigureScoreRewardBehaviorCommand,
  ConfigureSpawnPrefabActionBehaviorCommand,
  ConfigureTimerTriggerBehaviorCommand,
  CreatedRenderer,
  CreateRendererOptions,
  DamageBehaviorRecipeSpec,
  DashActionBehaviorRecipeSpec,
  DiagnosticCode,
  DiagnosticContext,
  DiagnosticReport,
  AccessibilityContrastColorRole,
  AccessibilityContrastPaletteName,
  AccessibilityContrastPaletteSpec,
  AccessibilityEnvironment,
  AccessibilityInputAssistSpec,
  AccessibilityMediaQueryListLike,
  AccessibilityMediaQuerySource,
  AccessibilityOptionsSpec,
  AccessibilityReducedMotionPreference,
  AccessibilitySubtitlePanelOptions,
  AccessibilitySubtitleSpec,
  DebugGizmoBoundsSpec,
  DebugGizmoCategory,
  DebugGizmoColor,
  DebugGizmoLine,
  DebugGizmoLineBufferResult,
  DebugGizmoOptions,
  DebugGizmoPathSpec,
  DebugGizmoPoint,
  DebugGizmoSceneSpec,
  DebugGizmoSpawnSpec,
  ResolvedDebugGizmoColor,
  ResolvedAccessibilityContrastPalette,
  ResolvedAccessibilityInputAssist,
  ResolvedAccessibilityOptions,
  ResolveAccessibilityOptionsOptions,
  RendererFallbackInfo,
  PhysicsReplayWorkerRunResult,
  PhysicsReplayWorkerTransferBenchmarkResult,
  BrowserPlatformHost,
  CreateEngineOptions,
  FerrumRuntime,
  FerrumRuntimeEnvironment,
  FerrumRuntimeFrame,
  FerrumRuntimeOptions,
  FerrumRuntimeRenderer,
  LightingSceneProvider,
  SpriteMaterialProvider,
  LoadingOverlayOptions,
  LoadingOverlayState,
  LoadingOverlayStatus,
  UiOverlayStateProvider,
  EngineLifecycleHooks,
  EngineLifecycleSnapshot,
  ActionFrameDiagnostics,
  SpawnFrameDiagnostics,
  AssetHost,
  FerrumEngine,
  FerrumGameplayAuthoringApi,
  FerrumInputActionApi,
  FixedTimestepOptions,
  FrameHandler,
  FrameState,
  CollisionDespawnBehaviorRecipeSpec,
  CollisionPickupBehaviorRecipeSpec,
  CollisionParticleBehaviorRecipeSpec,
  HealthBehaviorRecipeSpec,
  FactionBehaviorRecipeSpec,
  LifetimeBehaviorRecipeSpec,
  MeleeActionBehaviorRecipeSpec,
  ProjectileActionBehaviorRecipeSpec,
  SpawnPrefabActionBehaviorRecipeSpec,
  TimerTriggerBehaviorRecipeSpec,
  ResolvedDashActionBehaviorRecipe,
  ResolvedCollisionDespawnBehaviorRecipe,
  ResolvedCollisionPickupBehaviorRecipe,
  ResolvedCollisionParticleBehaviorRecipe,
  ResolvedMeleeActionBehaviorRecipe,
  ResolvedProjectileActionBehaviorRecipe,
  ResolvedSpawnPrefabActionBehaviorRecipe,
  ResolvedTimerTriggerBehaviorRecipe,
  GameStateSceneSnapshot,
  GameStateSnapshot,
  GameStateSnapshotJsonValue,
  GameStateSnapshotRestoreResult,
  GameStateSnapshotStorage,
  GameplayReplayComparison,
  GameplayReplayFrameSnapshot,
  GameplayReplayRun,
  GameplayReplaySnapshotDiff,
  GameplayBehaviorBindingSpec,
  GameplayActionDiagnosticCode,
  GameplayActionDiagnosticReport,
  GameplayActionDiagnosticReportOptions,
  GameplayActionDiagnosticValue,
  GameplaySpawnDiagnosticCode,
  GameplaySpawnDiagnosticExpectation,
  GameplaySpawnDiagnosticMetric,
  GameplaySpawnDiagnosticReport,
  GameplaySpawnDiagnosticReportOptions,
  GameplaySpawnDiagnosticValue,
  GameplayActionFailedEventAction,
  GameplayActionFailureReason,
  GameplayBehaviorStateChangedEventAction,
  GameplayBehaviorRuntimeIds,
  GameplayEntityHandle,
  GameplayEntityHandleMap,
  ResolveGameplayBehaviorRuntimeIdsOptions,
  GameplayCollisionDamageEventAction,
  GameplayCollisionDespawnEventAction,
  GameplayEventAction,
  GameplayEventActionApplyResult,
  GameplayEventActionMetadataMap,
  GameplayEventActionMetadataOptions,
  GameplayEventActionNameMap,
  GameplayEventActionOptions,
  GameplayEventActionTarget,
  GameplayFactionDamageDeniedEventAction,
  GameplayInteractionActionMetadata,
  GameplayInteractionEventAction,
  GameplayPickupCollectedEventAction,
  GameplayPrefabSpawnedEventAction,
  GameplayTimerEventAction,
  GameplayTileImpactEventAction,
  GameplayTileImpactNormal,
  GameplayTileImpactPolicy,
  InputManagerOptions,
  GamepadInputMapping,
  InputActionActivation,
  InputActionBinding,
  InputActionProfile,
  InputActionProfileId,
  InputActionRuntimeBinding,
  InputActionRuntimeControl,
  InputActionState,
  InputAxisBinding,
  InputDigitalControl,
  InputProvider,
  VirtualButtonOptions,
  VirtualControlsOptions,
  VirtualControlsState,
  VirtualJoystickOptions,
  ResolvedSpriteMaterialColorMix,
  ResolvedSpriteMaterialOutline,
  ResolvedSpriteMaterialPreset,
  SpriteMaterialBlendMode,
  SpriteMaterialColor,
  SpriteMaterialColorMix,
  SpriteMaterialOutlineDirections,
  SpriteMaterialOutlineOptions,
  SpriteMaterialPass,
  SpriteMaterialPreset,
  SpriteMaterialPresetInput,
  SpriteMaterialPresetName,
  LightingScene2D,
  LightingShadowOptions,
  Hd2dTileOccluderDefinition,
  Hd2dTileOccluderGridInput,
  PointLight2D,
  ResolvedLightingShadowOptions,
  ResolvedLightingScene2D,
  TileOccluder2D,
  TileOccluderGridInput,
  ShadowClipRect,
  ShadowProjectionOptions,
  IndexedDbAssetCacheOptions,
  JsonAssetCache,
  JsonCacheSetOptions,
  PhysicsAabbTileObstacleContactQuery,
  PhysicsAabbTileObstacleManifoldQuery,
  PhysicsDebugLineCamera,
  PhysicsDebugOptions,
  PhysicsDebugSpec,
  PhysicsFrameStats,
  PhysicsFloorId,
  PhysicsHd2dSpec,
  PhysicsHd2dKinematicMoveOptions,
  PhysicsHd2dKinematicMoveResult,
  PhysicsLayerPattern,
  PhysicsLayerSpec,
  PhysicsMaterialPresetName,
  PhysicsMode,
  PhysicsSpec,
  PhysicsAabbBodyShapeCastQuery,
  PhysicsAabbBodyQuery,
  PhysicsAabbTileObstacleShapeCastQuery,
  PhysicsAuthoringJointHandle,
  PhysicsAuthoringLayer,
  PhysicsBodyColliderOptions,
  PhysicsBodyColliderSnapshot,
  PhysicsBodyHeightSpan,
  PhysicsBodyHeightSpanQuery,
  PhysicsBodyStateBufferSnapshot,
  PhysicsBodyContactHit,
  PhysicsBodyContactHitBufferView,
  PhysicsBodyContactQuery,
  PhysicsBodyManifoldHit,
  PhysicsBodyManifoldHitBufferView,
  PhysicsBodyManifoldQuery,
  PhysicsBodyQueryHit,
  PhysicsCapsuleBodyShapeCastQuery,
  PhysicsCapsuleBodyQuery,
  PhysicsCircleBodyShapeCastQuery,
  PhysicsCircleBodyQuery,
  PhysicsConvexPolygonBodyShapeCastQuery,
  PhysicsConvexPolygonBodyQuery,
  PhysicsConvexPolygonVertexBuffer,
  PhysicsColliderAuthoringOptions,
  PhysicsColliderType,
  PhysicsCollisionLayer,
  PhysicsEntityHandle,
  PhysicsEntitySnapshot,
  PhysicsJointBaseOptions,
  PhysicsJointAuthoringOptions,
  PhysicsJointHandle,
  PhysicsJointSnapshot,
  PhysicsJointSpawnOptions,
  PhysicsJointType,
  ParticleColor,
  ParticlePresetConfig,
  ParticleRangeInput,
  ParticleTextureRef,
  ParticleUvRect,
  ParticleVfxEmitterConfig,
  ParticleVfxEmitterMode,
  ParticleVfxEmitterOptions,
  ParticleVfxEmitterSnapshot,
  ParticleVfxEmitterTarget,
  ParticleVfxPresetConfig,
  ParticleVfxPresetName,
  ResolvedParticleVfxEmitterConfig,
  ResolvedParticleVfxPresetConfig,
  PhysicsNearestBodyHit,
  PhysicsNearestBodyQuery,
  PhysicsNearestTileObstacleHit,
  PhysicsNearestTileObstacleQuery,
  PhysicsOrientedBoxBodyQuery,
  PhysicsPointBodyQuery,
  PhysicsQueryHitBufferView,
  PhysicsRaycastBodyHit,
  PhysicsRaycastBodyQuery,
  PhysicsRaycastHitBufferView,
  PhysicsRaycastTileObstacleQuery,
  PhysicsRigidContactImpulseHit,
  PhysicsRigidContactImpulseHitBufferView,
  PhysicsRigidBodyAuthoringOptions,
  PhysicsRigidBodyCollider,
  PhysicsRigidBodyMassProperties,
  PhysicsRigidBodyMaterial,
  PhysicsRigidBodySpawnOptions,
  PhysicsRigidBodyStepOptions,
  PhysicsRigidBodyStepStats,
  PhysicsRigidBodyTuning,
  PhysicsRigidBodyType,
  PhysicsMaterialSnapshot,
  PhysicsSegmentCastBodyQuery,
  PhysicsSegmentCastTileObstacleQuery,
  PhysicsShapeCastBodyHit,
  PhysicsShapeCastHitBufferView,
  PhysicsTileContactHit,
  PhysicsTileContactHitBufferView,
  PhysicsTileHeightSpan,
  PhysicsTileHeightSpanQuery,
  PhysicsTileManifoldHit,
  PhysicsTileManifoldHitBufferView,
  PhysicsTileRaycastHit,
  PhysicsTileRaycastHitBufferView,
  PhysicsTileShapeCastHit,
  PhysicsTileShapeCastHitBufferView,
  PhysicsTileShapeCastMotionQuery,
  PhysicsOrientedBoxBodyShapeCastQuery,
  PhysicsReplayInputEvent,
  PhysicsReplayInputRunResult,
  PhysicsReplayInputStream,
  PhysicsWorldApplyResult,
  ApplyPhysicsSceneProfileOptions,
  PhysicsSceneProfileApplyResult,
  PhysicsSceneProfileId,
  PhysicsSceneProfileSpec,
  PixelMaskTerrainAlphaPatch,
  PixelMaskTerrainBoundaryOptions,
  PixelMaskTerrainDirtyRect,
  PixelMaskTerrainLayerOptions,
  PixelMaskTerrainOptions,
  PixelMaskTerrainRuntimeOptions,
  PixelMaskTerrainRuntimeSyncResult,
  PixelMaskTerrainTextureTarget,
  PixelMaskTerrainTextureUploadOptions,
  Renderer,
  RendererStats,
  RuntimeDiagnosticsBudget,
  RuntimeDiagnosticsFrameSample,
  RuntimeDiagnosticsReport,
  RuntimeDiagnosticsViolation,
  RuntimeProfilerOptions,
  RuntimeProfilerSnapshot,
  ResolvedPhysicsHd2dSpec,
  ResolvedAnimationTimelineEvent,
  ResolvedAnimationTimelineSpec,
  ResolvedAnimationTimelineState,
  ResolvedAnimationTimelineTransition,
  ResolveBehaviorRecipeDocumentOptions,
  ResolveBehaviorStateMachineDocumentOptions,
  ResolvedBehaviorRecipe,
  ResolvedBehaviorRecipeBase,
  ResolvedBehaviorRecipeDocument,
  ResolvedBehaviorRecipeEntity,
  ResolvedBehaviorStateMachine,
  ResolvedBehaviorStateMachineDocument,
  ResolvedBehaviorStateMachineState,
  ResolvedBehaviorStateMachineTransition,
  ResolvedBehaviorStateMachineTransitionPredicate,
  ResolvedChaseBehaviorRecipe,
  ResolvedDamageBehaviorRecipe,
  ResolvedFactionBehaviorRecipe,
  ResolvedHealthBehaviorRecipe,
  ResolvedInteractionBehaviorRecipe,
  ResolvedLifetimeBehaviorRecipe,
  ResolvedPickupBehaviorRecipe,
  ResolvedScoreRewardBehaviorRecipe,
  ResolvedSceneCompositionFragment,
  ResolvedSceneCompositionFragmentInclude,
  ResolvedSceneCompositionFragmentInstance,
  ResolvedSceneCompositionInstance,
  ResolvedSceneCompositionPrefab,
  ResolvedSceneCompositionPrefabVariant,
  ResolvedSceneCompositionSpec,
  ResolvedSceneCompositionTransform,
  ResolveSceneCompositionOptions,
  SceneBehaviorBindingDryRunResult,
  SceneBehaviorBindingOptions,
  SceneBehaviorBindingPlan,
  SceneCompositionApplyResult,
  SceneCompositionFragmentIncludeSpec,
  SceneCompositionFragmentInstanceSpec,
  SceneCompositionFragmentSpec,
  SceneCompositionJsonValue,
  SceneCompositionPrefabSpec,
  SceneCompositionPrefabVariantSpec,
  SceneCompositionProps,
  SceneCompositionSpec,
  SceneCompositionTarget,
  SceneCompositionTransformSpec,
  InstantiateSceneFragmentOptions,
  PickupBehaviorRecipeSpec,
  CreateAssetPreloadCachePolicyOptions,
  InvalidatePreloadedAssetCacheOptions,
  PreloadAssetManifestOptions,
  PreloadedAssetManifest,
  InteractionBehaviorRecipeSpec,
  LDtkEntityInstance,
  LDtkTilemapImportOptions,
  LDtkTilemapImportResult,
  LDtkTilesetFrameContext,
  ResolvedShooterAtlasAnimation,
  ResolvedShooterAtlasAnimationState,
  ResolvedShooterPhysicsMaterial,
  ResolvedShooterPrefabColliderBase,
  ResolvedShooterPrefabCollider,
  ResolvedShooterPrefabColliderVertex,
  ShooterPrefabColliderType,
  ShooterAtlasFrameSpec,
  ShooterAtlasSpec,
  ShooterAtlasAnimationSpec,
  ShooterAtlasAnimationStateSpec,
  ShooterCameraPreset,
  ShooterCameraSpec,
  ShooterEnemyOrbitSpec,
  ShooterEnemyPresetSpec,
  ShooterGameSpec,
  ShooterPhysicsMaterialSpec,
  ShooterProjectileArcSpec,
  ShooterPrefabColliderSpec,
  ShooterTileBridgePortalSpec,
  ShooterTileKind,
  ShooterTileLayerSpec,
  ShooterTileRampAxis,
  ShooterTileRampSpec,
  ShooterTilemapSpec,
  ShooterTileSlopeSpec,
  ShooterTileSpec,
  ResolvedShooterTileDefinition,
  ResolvedShooterTileBridgePortalDefinition,
  ResolvedShooterTileRampDefinition,
  ResolvedShooterTileSlopeDefinition,
  ShooterWaveSpec,
  ResolvedShooterProjectileArcSpec,
  ResolvedShooterTilemap,
  ViewportProvider,
  WebGPURenderer,
  WebGPURendererOptions,
  WebGL2RendererOptions,
  CollisionEventBufferView,
  CollisionEventView,
  CameraBounds,
  CameraDeadZone,
  CameraPoint,
  CameraRigSnapshot,
  CameraRigSpec,
  CameraRigStepOptions,
  CameraViewport,
  PhysicsDebugLineBufferView,
  PhysicsDebugLineView,
  BloomPostProcessPassInput,
  CrtPostProcessPassInput,
  FadePostProcessPassInput,
  GlitchPostProcessPassInput,
  PostProcessColor,
  PostProcessPassInput,
  PostProcessPassKind,
  PostProcessingConfigInput,
  PostProcessProvider,
  PostProcessStackInput,
  VignettePostProcessPassInput,
  CutsceneAudioAction,
  CutsceneAudioBus,
  CutsceneAudioCommandSpec,
  CutsceneCameraCommandSpec,
  CutsceneCommandBaseSpec,
  CutsceneDialogueCommandSpec,
  CutsceneSequenceCommandKind,
  CutsceneSequenceCommandSpec,
  CutsceneSequenceEasing,
  CutsceneSequenceEvent,
  CutsceneSequencePlayerSnapshot,
  CutsceneSequenceSpec,
  CutsceneSequenceTarget,
  CutsceneSequenceUpdateOptions,
  CutsceneSequenceUpdateResult,
  CutsceneWaitCommandSpec,
  ResolveCutsceneSequenceOptions,
  ResolvedCutsceneAudioCommand,
  ResolvedCutsceneCameraCommand,
  ResolvedCutsceneCommandBase,
  ResolvedCutsceneDialogueCommand,
  ResolvedCutsceneSequenceCommand,
  ResolvedCutsceneSequenceSpec,
  ResolvedCutsceneWaitCommand,
  BitmapFontPolicySpec,
  FontDisplayPolicy,
  FontFaceSetLike,
  FontLoadingPolicySpec,
  LoadFontPolicyResult,
  LocalizationDocumentSpec,
  LocalizationLocaleSpec,
  LocalizationPlaceholderValue,
  LocalizationStringEntrySpec,
  LocalizationStringSpec,
  LocalizeOptions,
  LocalizedTextResult,
  MissingLocalizationBehavior,
  MissingSceneBehaviorBinding,
  UnknownGameplayEventPolicy,
  ScoreRewardBehaviorRecipeSpec,
  ResolvedBitmapFontPolicy,
  ResolvedCameraBounds,
  ResolvedCameraDeadZone,
  ResolvedCameraRigSpec,
  ResolvedBloomPostProcessPass,
  ResolvedCrtPostProcessPass,
  ResolvedFontLoadingPolicy,
  ResolvedFadePostProcessPass,
  ResolvedGlitchPostProcessPass,
  ResolvedLocalizationDocument,
  ResolvedLocalizationLocale,
  ResolvedLocalizationString,
  ResolvedPostProcessColor,
  ResolvedPostProcessPass,
  ResolvedVignettePostProcessPass,
  ResolvedWebFontPolicy,
  ResolveCameraRigOptions,
  ResolveLocalizationOptions,
  ResolvePostProcessOptions,
  TextDirection,
  TextLayoutLine,
  TextLayoutOptions,
  TextLayoutResult,
  WebFontPolicySpec,
  LevelChunkBounds,
  LevelChunkManifestSpec,
  LevelChunkSpec,
  LevelChunkStreamerSnapshot,
  LevelStreamingAssetLifetimePolicy,
  LevelStreamingOrigin,
  LevelStreamingPlan,
  LevelStreamingPlanOptions,
  LevelStreamingViewport,
  LevelTilemapChunkSpec,
  ResolveLevelChunkManifestOptions,
  ResolvedLevelChunk,
  ResolvedLevelChunkManifest,
  ResolvedLevelTilemapChunk,
  DialogueChoiceResult,
  DialogueChoiceSpec,
  DialogueGraphSpec,
  DialogueNodeSpec,
  DialogueQuestStateSnapshot,
  DialogueSessionSnapshot,
  DialogueUiOptions,
  QuestDocumentSpec,
  QuestLogSnapshot,
  QuestObjectiveSpec,
  QuestProgressSnapshot,
  QuestSpec,
  QuestStageSpec,
  QuestStatus,
  QuestUpdateAction,
  QuestUpdateSpec,
  ResolvedDialogueChoice,
  ResolvedDialogueGraph,
  ResolvedDialogueNode,
  ResolvedQuest,
  ResolvedQuestDocument,
  ResolvedQuestObjective,
  ResolvedQuestStage,
  ResolvedQuestUpdate,
  ResolveDialogueQuestOptions,
  RestoreDialogueQuestStateOptions,
  TiledLayerCompressionContext,
  TiledLayerDataDecoder,
  TiledTilemapImportOptions,
  TiledTilemapImportResult,
  TiledTilesetFrameContext,
  TilemapNavigationPath,
  TilemapNavigationPathPoint,
  TilemapNavigationPathQuery,
  TilemapNavigationWaypoint,
  TilemapNavigationWaypointQuery,
  TilemapRectEditOptions,
  TileRuleGrid,
  TileRuleSpec,
  TilemapBoundaryChain,
  TilemapBoundaryExtractionOptions,
  TilemapBoundaryExtractionResult,
  CreateHudOverlayStateOptions,
  HudComponentBase,
  HudComponentSpec,
  HudCounterSpec,
  HudMessageSpec,
  HudMeterSpec,
  HudPromptSpec,
  HudThemeInput,
  HudThemePresetName,
  HudThemeTokens,
  ResolvedHudThemeTokens,
  UiAction,
  UiDialog,
  UiMeter,
  UiOverlay,
  UiOverlayActionEvent,
  UiOverlayActionTone,
  UiOverlayOptions,
  UiOverlayRegion,
  UiOverlayState,
  UiOverlayTone,
  UiPanel,
  UiTextLine,
  ScreenFadeTransitionSnapshot,
  ScreenFadeTransitionSpec,
  createFerrumRuntime,
  generateTextureAtlasLayout,
} from "../src/index.js";

export type PublicApi = typeof import("../src/index.js");
export type AssertType<T extends true> = T;
export type IfEquals<X, Y, A = true, B = false> =
  (<T>() => T extends X ? 1 : 2) extends
  (<T>() => T extends Y ? 1 : 2) ? A : B;
export type IsReadonly<T, K extends keyof T> = IfEquals<
  { [P in K]: T[P] },
  { -readonly [P in K]: T[P] },
  false,
  true
>;
type _BuiltInShooterSnapshotEntityCountReadonly = AssertType<IsReadonly<BuiltInShooterStateSnapshot, "entityCount">>;
type _GameStateSceneSnapshotScoreReadonly = AssertType<IsReadonly<GameStateSceneSnapshot, "score">>;
type _GameStateSnapshotSceneReadonly = AssertType<IsReadonly<GameStateSnapshot, "scene">>;
type _GameStateSnapshotRestoreResultSceneAfterReadonly = AssertType<IsReadonly<GameStateSnapshotRestoreResult, "sceneAfter">>;
export const readonlySnapshotTypeAssertions: [
  _BuiltInShooterSnapshotEntityCountReadonly,
  _GameStateSceneSnapshotScoreReadonly,
  _GameStateSnapshotSceneReadonly,
  _GameStateSnapshotRestoreResultSceneAfterReadonly,
] = [true, true, true, true];

export function f32Bits(value: number): number {
  const damage = new Float32Array([value]);
  return new Uint32Array(damage.buffer)[0];
}
