export { applyShooterGameSpec, resolveShooterGameSpec } from "../gameSpec";
export { FerrumDiagnosticError, diagnosticReport, formatDiagnosticReport, isFerrumDiagnosticError } from "../diagnostics";
export type { DiagnosticCode, DiagnosticContext, DiagnosticKind, DiagnosticReport } from "../diagnostics";
export {
  compilePhysicsAuthoringDocument,
  isPhysicsAuthoringDocument,
  PHYSICS_AUTHORING_SCHEMA_VERSION,
  validatePhysicsAuthoringDocument,
} from "../physicsAuthoringSchema";
export type {
  CompilePhysicsAuthoringOptions,
  PhysicsAuthoringDocument,
  PhysicsEditorBodyMetadata,
  PhysicsEditorGizmoKind,
  PhysicsEditorJointMetadata,
  PhysicsEditorMetadata,
  PhysicsEditorPresetMetadata,
} from "../physicsAuthoringSchema";
export {
  capturePhysicsWorldSnapshot,
  createPhysicsReplayInputStream,
  hashPhysicsWorldSnapshot,
  PHYSICS_REPLAY_INPUT_STREAM_FORMAT,
  PHYSICS_REPLAY_INPUT_STREAM_VERSION,
  PHYSICS_WORLD_SNAPSHOT_FORMAT,
  PHYSICS_WORLD_SNAPSHOT_VERSION,
  restorePhysicsWorldSnapshot,
  runPhysicsReplayInputStream,
  verifyPhysicsReplayInputStreamRollback,
  verifyPhysicsReplayRollback,
} from "../physicsSnapshot";
export type {
  CapturePhysicsWorldSnapshotOptions,
  PhysicsReplayApplyForceEvent,
  PhysicsReplayApplyImpulseEvent,
  PhysicsReplayFrameSnapshot,
  PhysicsReplayInputEvent,
  PhysicsReplayInputEventBase,
  PhysicsReplayInputRollbackOptions,
  PhysicsReplayInputRollbackResult,
  PhysicsReplayInputRunOptions,
  PhysicsReplayInputRunResult,
  PhysicsReplayInputStream,
  PhysicsReplayRollbackOptions,
  PhysicsReplayRollbackResult,
  PhysicsReplaySetEnabledEvent,
  PhysicsReplaySetPositionEvent,
  PhysicsReplaySetVelocityEvent,
  PhysicsWorldRestoreResult,
  PhysicsWorldSnapshot,
  PhysicsWorldSnapshotBody,
  PhysicsWorldSnapshotCollider,
  PhysicsWorldSnapshotHashOptions,
  PhysicsWorldSnapshotJoint,
  RestorePhysicsWorldSnapshotOptions,
} from "../physicsSnapshot";
export {
  PHYSICS_REPLAY_WORKER_REQUEST_FORMAT,
  PHYSICS_REPLAY_WORKER_RESPONSE_FORMAT,
  PHYSICS_REPLAY_WORKER_VERSION,
  PhysicsReplayWorkerClient,
  createPhysicsReplayWorkerClient,
} from "../physicsReplayWorker";
export type {
  CreatePhysicsReplayWorkerClientOptions,
  PhysicsReplayWorkerError,
  PhysicsReplayWorkerPort,
  PhysicsReplayWorkerRequest,
  PhysicsReplayWorkerResponse,
  PhysicsReplayWorkerRunOptions,
  PhysicsReplayWorkerRunResult,
  PhysicsReplayWorkerTransferBenchmarkOptions,
  PhysicsReplayWorkerTransferBenchmarkResult,
  PhysicsReplayWorkerTransferBenchmarkSample,
} from "../physicsReplayWorker";
export {
  PHYSICS_BUILTIN_COLLISION_LAYERS,
  PHYSICS_COMMON_LAYER_PATTERN,
  PHYSICS_MATERIAL_PRESETS,
  clearPhysicsWorld,
  createCollider,
  createJoint,
  createPhysicsLayerMap,
  createPhysicsLayerSpec,
  createPhysicsWorldFromSpec,
  createRigidBody,
  createVehicleRig,
  physicsLayerMaskBits,
  physicsMaterial,
} from "../physicsAuthoring";
export type {
  PhysicsAuthoringContext,
  PhysicsAuthoringJointHandle,
  PhysicsAuthoringLayer,
  PhysicsColliderAuthoringOptions,
  PhysicsJointAuthoringOptions,
  PhysicsJointEndpoint,
  PhysicsLayerMapOptions,
  PhysicsLayerPattern,
  PhysicsLayerPatternEntry,
  PhysicsMaterialAuthoringInput,
  PhysicsMaterialPresetName,
  PhysicsRigidBodyAuthoringOptions,
  PhysicsVehicleRigAuthoringOptions,
  PhysicsVehicleRigResult,
  PhysicsVehicleWheelAuthoringOptions,
  PhysicsWorldApplyOptions,
  PhysicsWorldApplyResult,
  PhysicsWorldApplyWarning,
} from "../physicsAuthoring";
export { applyPhysicsSceneProfile } from "../physicsSceneIntegration";
export type {
  ApplyPhysicsSceneProfileOptions,
  PhysicsSceneProfileApplyResult,
  PhysicsSceneProfileId,
  PhysicsSceneProfileSpec,
} from "../physicsSceneIntegration";
export {
  PixelMaskTerrain,
  createPixelMaskTerrain,
  extractPixelMaskBoundaryChains,
  pixelMaskTerrainToTilemapLayer,
} from "../pixelMaskTerrain";
export type {
  PixelMaskTerrainAlphaPatch,
  PixelMaskTerrainBoundaryOptions,
  PixelMaskTerrainDirtyRect,
  PixelMaskTerrainLayerOptions,
  PixelMaskTerrainOptions,
  PixelMaskTerrainTextureUploadOptions,
} from "../pixelMaskTerrain";
export { PixelMaskTerrainRuntime, createPixelMaskTerrainRuntime } from "../pixelMaskTerrainRuntime";
export type {
  PixelMaskTerrainRuntimeOptions,
  PixelMaskTerrainRuntimePhysicsOptions,
  PixelMaskTerrainRuntimeSyncOptions,
  PixelMaskTerrainRuntimeSyncResult,
  PixelMaskTerrainRuntimeTextureOptions,
  PixelMaskTerrainTextureTarget,
} from "../pixelMaskTerrainRuntime";
export { extractTilemapBoundaryChains } from "../tilemapPhysics";
export type {
  TilemapBoundaryChain,
  TilemapBoundaryExtractionOptions,
  TilemapBoundaryExtractionResult,
} from "../tilemapPhysics";
export { DEFAULT_PHYSICS_MODE, resolvePhysicsMode, resolvePhysicsSpec } from "../physicsSpec";
export type {
  PhysicsBodySpec,
  PhysicsBoxColliderSpec,
  PhysicsCapsuleColliderSpec,
  PhysicsChainColliderSpec,
  PhysicsCircleColliderSpec,
  PhysicsColliderSpec,
  PhysicsConvexPolygonColliderSpec,
  PhysicsDebugSpec,
  PhysicsEdgeColliderSpec,
  PhysicsFloorId,
  PhysicsHd2dSpec,
  PhysicsJointLimitSpec,
  PhysicsJointMotorSpec,
  PhysicsJointSpec,
  PhysicsLayerSpec,
  PhysicsMaterialSpec,
  PhysicsMode,
  PhysicsOrientedBoxColliderSpec,
  PhysicsSolverSpec,
  PhysicsSpec,
  PhysicsSpecBodyType,
  PhysicsSpecColliderShape,
  PhysicsSpecJointType,
  PhysicsSpecVector2,
  ResolvedPhysicsBodySpec,
  ResolvedPhysicsBoxColliderSpec,
  ResolvedPhysicsCapsuleColliderSpec,
  ResolvedPhysicsChainColliderSpec,
  ResolvedPhysicsCircleColliderSpec,
  ResolvedPhysicsColliderBaseSpec,
  ResolvedPhysicsColliderSpec,
  ResolvedPhysicsDebugSpec,
  ResolvedPhysicsEdgeColliderSpec,
  ResolvedPhysicsHd2dSpec,
  ResolvedPhysicsJointSpec,
  ResolvedPhysicsLayerSpec,
  ResolvedPhysicsMaterialSpec,
  ResolvedPhysicsOrientedBoxColliderSpec,
  ResolvedPhysicsSolverSpec,
  ResolvedPhysicsSpec,
  ResolvedPhysicsVector2,
  ResolvePhysicsSpecOptions,
} from "../physicsSpec";
export type {
  ApplyShooterGameSpecOptions,
  ResolveShooterGameSpecOptions,
  ResolvedShooterAtlasAnimation,
  ResolvedShooterAtlasAnimationState,
  ResolvedShooterAtlasFrame,
  ResolvedShooterGameSpec,
  ResolvedShooterPhysicsMaterial,
  ResolvedShooterPrefabAabbCollider,
  ResolvedShooterPrefabColliderBase,
  ResolvedShooterPrefabCollider,
  ResolvedShooterPrefabColliderVertex,
  ResolvedShooterWave,
  ShooterAtlasAnimationSpec,
  ShooterAtlasAnimationStateSpec,
  ShooterAudioEventPolicySpec,
  ShooterAudioSpec,
  ShooterAtlasFrameSpec,
  ShooterAtlasSpec,
  ShooterCameraPreset,
  ShooterCameraSpec,
  ShooterEnemyBehaviorPreset,
  ShooterEnemyOrbitSpec,
  ShooterEnemyPresetSpec,
  ShooterGameSpec,
  ShooterGameSpecTarget,
  ShooterPhysicsMaterialSpec,
  ShooterProjectileArcSpec,
  ShooterPrefabColliderSpec,
  ShooterPrefabColliderType,
  ShooterPrefabSpec,
  ShooterTileBridgePortalSpec,
  ShooterTileKind,
  ShooterTileLayerSpec,
  ShooterTileRampAxis,
  ShooterTileRampSpec,
  ShooterTilemapSpec,
  ShooterTileSlopeSpec,
  ShooterTileSpec,
  ResolvedShooterTileDefinition,
  ResolvedShooterTileBridgePortalDefinition,
  ResolvedShooterTileLayer,
  ResolvedShooterTileRampDefinition,
  ResolvedShooterTileSlopeDefinition,
  ResolvedShooterTilemap,
  ShooterWaveSpec,
  ResolvedShooterProjectileArcSpec,
} from "../gameSpec";
export type {
  ParticleColor,
  ParticlePresetConfig,
  ParticleRangeInput,
  ParticleTextureRef,
  ParticleUvRect,
} from "../particlePreset";
export type {
  ParticleVfxEmitterConfig,
  ParticleVfxEmitterMode,
  ParticleVfxEmitterOptions,
  ParticleVfxEmitterSnapshot,
  ParticleVfxEmitterTarget,
  ParticleVfxPresetConfig,
  ParticleVfxPresetName,
  ResolvedParticleVfxEmitterConfig,
  ResolvedParticleVfxPresetConfig,
} from "../particleVfx";
